### ISSUE TITLE
Setup.sh breaks on bookworm

### ISSUE THREAD

**Issue by Sejl** [aaronwmorris/indi-allsky#1003]
Hi. I have been trying to install indi-allsky on raspberry without success.
I have tried on raspberry pi v3 b+ and raspberry pi 4 compute module.
On both I have installed latest bookworm 32bit lite. Indi was compiled without 3rd party libraries.

Error that I get from setup.sh is:

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libimath-dev : Conflicts: libilmbase-dev
 libopenexr-dev : Breaks: libilmbase-dev (< 2.5.7-3~)
E: Unable to correct problems, you have held broken packages.

The script exited abnormally, please try to run again...

I will now try to install with bullseye to see if the problem persists.
Thank you for any suggestion.

Best regards

**Comment by Sejl** [comment]
Just to report that bullseye does not have this problem.
Everything goes smoothly.

Best regards

**Comment by aaronwmorris** [comment]
This is a problem with packages in the 32-bit version of bookworm.  Everything should work fine with the 64-bit release.

**Comment by Sejl** [comment]
Thank you!
I will try with 64bit release.

Best regards

**Comment by aaronwmorris** [comment]
Did the 64-bit release work any better for you?

**Comment by Sejl** [comment]
> Did the 64-bit release work any better for you?

Yes! 
Sorry for the late reply 🙈

It works on bookworm 64-bit on rpi compute module 4.

Thank you for your help!

Best regards

**Comment by aaronwmorris** [comment]
Closing for now.  Let me know if I can do anything else!
