### ISSUE TITLE
v7.6 release - keogram/startrail broken at night?

### ISSUE THREAD

**Issue by StarGeezerPhil** [aaronwmorris/indi-allsky#1004]
@aaronwmorris upgraded straight to 7.6 after receiving the notification.

Not had chance to check through the log files etc. yet, but noticed that night time timelapses etc. seem to be broken since the update:

![image](https://github.com/aaronwmorris/indi-allsky/assets/94135145/0cb87546-6253-4574-8fb5-16afa101d641)

The timelapse video works absolutely fine, but the keogram and holding image for the star trail seems to be missing. Abysmal weather here so can't comment about actual star trail generation or the star trail timelapse video.

**Comment by aaronwmorris** [comment]
My guess is it is related to #1001 assuming you are using a detection mask.  You may need to generate a new detection mask based on the new way of processing the mask.

Let me know if you need some guidance on this, it is very new.

**Comment by StarGeezerPhil** [comment]
Yes, using detection mask, but it's the original dimensions and matches the mask_base.png (thanks for adding this as a reference file - very useful! 👍).

**Comment by aaronwmorris** [comment]
You may have to try to generate the startrails/keogram again and reference the logs for errors.  I did some basic testing before releasing, but only with a virtual camera.  Currently, my cameras are packed up due to moving, so I have not tested as much as I would have liked.

**Comment by aaronwmorris** [comment]
Today I merged #1006 because I forgot to include the scaling step for the mask.  I do not think this will help you, but maybe...

**Comment by aaronwmorris** [comment]
#1008 Another fix.  I will get this right eventually.

**Comment by StarGeezerPhil** [comment]
Brilliant @aaronwmorris - that's fixed it 👍🔥
