### ISSUE TITLE
QHY5III485C Focus Mode

### ISSUE THREAD

**Issue by sadowskiphoto** [aaronwmorris/indi-allsky#1023]
Hi- I have correctly installed indi-allsky, however, when my QHY5III485C shows black screen and no image when using focus mode. I have verified connection using K-Stars and Ekos...and have also made sure i dont have any conflicting server issues. I am using local mode. Looking forward to your advice and using indi-allsky!! Thank you in advance...

**Comment by aaronwmorris** [comment]
If the screen is black, it sounds like maybe the exposure has not scaled up to where you can see anything.  You might try setting a default exposure of 0.1 or 1.0 to see if it will start showing something.

**Comment by sadowskiphoto** [comment]
I tried that and it only shows black - i also rebooted system....strange. I have the cardinal points, time, etc overlay but no image. Is there a way to force a qhy ccd driver update on to the system?

**Comment by aaronwmorris** [comment]
Do you get an image without focus mode?

**Comment by sadowskiphoto** [comment]
Hi- no that too does not work...in my hunt i realized i maybe missing the /lib/firmware/qhy/QHY5III485.img  firmware....do you have a suggestion for this? i am trying to update the recommended fxload suggestion
 for this camera

**Comment by aaronwmorris** [comment]
If the problem were a missing firmware, you should not get any image at all since the camera would not be detected.  If you are seeing a black screen, are you sure you are not using the CCD Simulator?

There are problems with fxload being compatible with QHY cameras with USB3.  This wiki page can help you with that:
https://github.com/aaronwmorris/indi-allsky/wiki/Build-fxload-for-USB3-support

**Comment by sadowskiphoto** [comment]
Thank you...I was just looking at that wiki page...seems that I dont have the firmware/qhy/QHY5III485.img accessible easily....i saw the driver logs and its all windows based...thx again for such prompt responses! Will look at ccd simulator reference

**Comment by sadowskiphoto** [comment]
I am reinstalling this time using Docker...have quick question about the setup..i have docker compose v2 but it mentions about using the setup_env.sh script. There is so such script available...can you advise? Here is my indi-allsky list:
LICENSE    config.py  examples             log                requirements
README.md  content    flask.json_template  migrations         service
allsky.py  darks.py   html                 misc               setup.sh
app.py     docker     indi_allsky          passenger_wsgi.py  testing

**Comment by aaronwmorris** [comment]
You just need to run the setup_env.sh script to create the files necessary for the docker build.

At this time, the docker build will fail, unfortunately due to the typo bug in INDI 2.0.4.  I have opened an issue with the INDI team to see if they will be willing to distribute the fix.

**Comment by sadowskiphoto** [comment]
Is there a work around for this in docker....something i can adjust to make docker work?

**Comment by aaronwmorris** [comment]
I am not a docker expert, but the problem has to be fixed during the image build phase.  One of the source files from INDI needs to be fixed and I do not know how to do that unless I manually include a patch during the image build process.

**Comment by aaronwmorris** [comment]
Merged #1036 to make Debian 12 the default base image for the INDI components.  The Debian image will compile INDI from source and I have v2.0.3 set as the default so this should by pass the bug in 2.0.4.

**Comment by aaronwmorris** [comment]
Closing this issue for now.  Please reopen if there is anything I missed.
