### ISSUE TITLE
Need help with two instances

### ISSUE THREAD

**Issue by warwound** [aaronwmorris/indi-allsky#1046]
My plan is to run two instances of indi-allsky on my 4GB Pi 5.
I have 2 HQ cameras connected, one with a wide angle lens and one with a telephoto lens.

I currently have a single instance installed the normal way (not using Docker) and it's working fine.
My 2 options must be:

#1
Install another instance the normal way and run it's webserver on a different port than the existing instance.
Is this possible, would I need to install and run the second instance as a different user than the existing instance?

#2
Use Docker to install and configure 2 different instances on 2 different ports.
Would each Docker instance be entirely self-contained - each would have their own INDIALLSKY_IMAGE_FOLDER etc?
I have no experience with Docker but have managed to build and start a single Docker instance.
(I did stop and disable all the services related to the existing non Docker instance).
My .env file contained the default line:

[code]
INDIALLSKY_INDI_CCD_DRIVER=indi_simulator_ccd
[/code]

I changed that to:

[code]
INDIALLSKY_INDI_CCD_DRIVER=indi
[/code]

I see no images captured and the Log page simply displays:

[quote]
ERROR: Log file missing
[/quote]

Are both options possible and, if so, which would be recommended?

**Comment by aaronwmorris** [comment]
Both may use the same image folder, but you probably want to use a different set of docker volumes for the second set of containers.  There are 4 volumes, so you will have to have a new name for each of those.

The CCD driver you probably want to use for these is probably `indi_simulator_ccd` since I assume you will want to use libcamera and not the indi interface.  You just need to change the interface from INDI to the correct libcamera device model in the config form (and restart the containers).

If you are using the libcamera interface, you will also want to enable the `privileged` flag on the capture container so that it may access the devices (look at the indiserver container settings).  I have not tested this, but it should work in theory.

**Comment by aaronwmorris** [comment]
In your case, you need the privileged flag on the capture container.

The log web view is not going to work with the docker deployment.  All of the logs will be available in the docker logging output.

**Comment by warwound** [comment]
Ah yes, I missed that.
The compose file actually reads:

#privileged: true  # enable for libcamera

I uncommented it, rebuilt 'capture.indi.allsky' then rebooted.
Unfortunately the problem persists and I see lots of 'BaseClientQt: Error. Unable to find driver libcamera_imx477' log lines while it's running.
I've attached my compose file, can you cofirm I modified it correctly?
[docker-compose.txt](https://github.com/aaronwmorris/indi-allsky/files/13539985/docker-compose.txt)

**Comment by aaronwmorris** [comment]
That error is normal.

I just realized that libcamera is not available on the base image I used.  Let me think about this.

**Comment by aaronwmorris** [comment]
Merged #1052 with compiling libcamera from source in the docker images.

Unfortunately, you will have to rebuild your images and there are a couple of more variables to add to your .env file.  I have no idea if running libcamera-still from a privileged container will actually work.

**Comment by warwound** [comment]
I deleted my .env file and re-ran the setup_env.sh script.
Then executed:

docker compose build --no-cache

I didn't spot any problems while it was building but it fails to run.
Attempts to connect to the web ui result in a '502 Proxy Error':

Reason: DNS lookup failure for: gunicorn.indi.allsky

The logs shows errors such as:

docker-gunicorn.indi.allsky-1    | mysql.connector.errors.ProgrammingError: 1045 (28000): Access denied for user 'indi_allsky_own'@'172.18.0.4' (using password: YES)
docker-gunicorn.indi.allsky-1    | sqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1045 (28000): Access denied for user 'indi_allsky_own'@'172.18.0.4' (using password: YES)
docker-webserver.indi.allsky-1   | [Tue Dec 05 18:15:54.525323 2023] [proxy:error] [pid 8:tid 140735882424608] [remote 10.10.30.49:51742] AH00898: DNS lookup failure for: gunicorn.indi.allsky returned by /indi-allsky/

So looks like something fails in the boot process and we don't even reach the stage where image capture occurs.
I've attached my docker-compose file and also the log lines.
[docker_pi5.lan_20231205.txt](https://github.com/aaronwmorris/indi-allsky/files/13567545/docker_pi5.lan_20231205.txt)
[docker-compose.txt](https://github.com/aaronwmorris/indi-allsky/files/13567546/docker-compose.txt)

**Comment by aaronwmorris** [comment]
Sure.  You can run `docker volume ls` to show the volumes that have been created.  You will probably have to delete your containers (not the images) to delete the volumes.

```
docker volume rm docker_database_indi_allsky
docker volume rm docker_images_indi_allsky
docker volume rm docker_migrations_indi_allsky
docker volume rm docker_mosquitto_data_indi_allsky
```

**Comment by aaronwmorris** [comment]
/usr/local/bin was missing from PATH on the capture container.  Merged #1055 to fix.

All you should have to do is pull down the latest code and rebuild the capture image.

```
docker compose build capture.indi.allsky
```

**Comment by warwound** [comment]
I tried again, this time the errors logged are like:

[quote]
docker-capture.indi.allsky-1     | 2023-12-08 15:49:24,145 [ERROR] Capture-1-63/MainThread libcamera.getCcdExposureStatus() #302: libcamera-still error: b'[0:05:39.039253983] [69] \x1b[1;32m INFO \x1b[1;37mCamera \x1b[1;34mcamera_manager.cpp:284 \x1b[0mlibcamera v0.0.0+1-563cd78e\n'
docker-capture.indi.allsky-1     | 2023-12-08 15:49:24,146 [ERROR] Capture-1-63/MainThread libcamera.getCcdExposureStatus() #302: libcamera-still error: b'ERROR: *** no cameras available ***\n'
docker-capture.indi.allsky-1     | 2023-12-08 15:49:24,146 [ERROR] Capture-1-63/MainThread libcamera._processMetadata() #322: Metadata file not found: [Errno 2] No such file or directory: '/tmp/tmpui1mdhlv.json'
docker-capture.indi.allsky-1     | 2023-12-08 15:49:24,146 [ERROR] Capture-1-63/MainThread libcamera._processMetadata() #345: libcamera sensor temperature key not found
docker-capture.indi.allsky-1     | 2023-12-08 15:49:24,146 [ERROR] Capture-1-63/MainThread libcamera._processMetadata() #424: libcamera sensor black level key not found
[quote]

The command:

libcamera-still --list-cameras

Lists both of my HQ cameras.

Log file attached.
[MobaXterm_pi5.lan_20231208_155114.txt](https://github.com/aaronwmorris/indi-allsky/files/13618454/MobaXterm_pi5.lan_20231208_155114.txt)

**Comment by aaronwmorris** [comment]
Just to double check, you have `privileged` enabled for the capture container?

**Comment by warwound** [comment]
Yes:

[quote]
  capture.indi.allsky:
    build:
      context: ..
      dockerfile: docker/Dockerfile.capture
    env_file: .env
    depends_on:
      - mariadb.indi.allsky
      - indiserver.indi.allsky
      - indi.allsky.base
    privileged: true  # enable for libcamera
    volumes:
      - images_indi_allsky:/var/www/html/allsky
       [/quote]

That's my compose file.

**Comment by aaronwmorris** [comment]
Well, that is unfortunate.  I have not been able to test this myself, but I have read some forum posts that this should be possible.

Try adding a device mapping config to your compose.

```yaml
capture.indi.allsky:
  build:
  context: ..
  dockerfile: docker/Dockerfile.capture
  env_file: .env
  depends_on:
    - mariadb.indi.allsky
    - indiserver.indi.allsky
    - indi.allsky.base
  privileged: true # enable for libcamera
  devices:
    - '/dev:/dev'
  volumes:
    - images_indi_allsky:/var/www/html/allsky
```

**Comment by aaronwmorris** [comment]
That first error is a normal error message.  indi-allsky tries to connect to a camera by that name via the indiserver, but it fails since it is using libcamera directly.

I will investigate more.  It is possible there is another group the `allsky` user (within the container) needs to be a member to detect and operate the camera [as a non-root user].

**Comment by aaronwmorris** [comment]
I managed to get libcamera working in a container in my Pi4.  Additional udev resources need to be accessible in the container.

This should make things work:
```json
  capture.indi.allsky:
    build:
      context: ..
      dockerfile: docker/Dockerfile.capture
    env_file: .env
    depends_on:
      - mariadb.indi.allsky
      - indiserver.indi.allsky
      - indi.allsky.base
    privileged: true  # enable for libcamera
    volumes:
      - images_indi_allsky:/var/www/html/allsky
      - /run/udev:/run/udev:ro  # enable for libcamera
```

**Comment by warwound** [comment]
Hallelujah it works!
Thanks a lot for all your efforts.
I shall now decide my next move.
(I want two instances of allsky and now have my 'normal install' and also the 'docker install' which gives me two instances without having to learn docker compose and 'how to run multiple instances').

**Comment by warwound** [comment]
I can report 3 problems with more than a single instance of allsky:

Trying to view each instance's web interface using the same browser results in a loop of being logged out.
Not a problem - at last I found a use for Edge lols.

I put my logo file in my Pi 5 /var/www/html/allsky folder and then used /var/www/html/allsky/my_overlay.png as the path in the Config > Processing > Logo Overlay setting.
Always resulting in an error 'file not found please fix'.

Wondering how to dark frame calibration.
All the instructions assume SSH access to execute commands.
I found the docker compose exec command and managed to open a shell on indiserver.indi.allsky
I looked around the file system but couldn't find where the 'darks.py' script was installed, so was unable to start calibrarion.

Can I use a shell to start the calibrartion and set my logo?

Thanks.

**Comment by aaronwmorris** [comment]
> Trying to view each instance's web interface using the same browser results in a loop of being logged out.

This is because you have the same hostname for each instance.  The session cookie is getting overridden when you switch between the instances.  If you create a new /etc/hosts entry on your machine you can avoid this.... or use different browsers for each.

> I put my logo file in my Pi 5 /var/www/html/allsky folder and then used /var/www/html/allsky/my_overlay.png as the path in the Config > Processing > Logo Overlay setting.
> Always resulting in an error 'file not found please fix'.

You will have to put the logo file in `/var/www/html/allsky/images/`.  That is the root folder that is shared among the containers.

> Wondering how to dark frame calibration.

I had not really considered dark frames with containers.  There will have to be a new container to support creating dark frames.

**Comment by warwound** [comment]
Thanks again for your time.

The cookie issue is not at all important to me at the moment, Firefix and Edge give me a simple solution.

I uploaded my logo image to:
/var/lib/docker/volumes/docker_images_indi_allsky/_data/images/logo_20231213.png
Then in the running docker instance, I set the 'Logo Overlay' setting to 'logo_20231213.png' and then '/logo_20231213.png' but still allsky complains 'File does not exist'.
What path do I need to use here?

**Comment by aaronwmorris** [comment]
It will be the full path inside the container.

`/var/www/html/allsky/images/logo_20231213.png`

**Comment by warwound** [comment]
Could I transfer the 'darkness calibration data/images' from my 'normal install' to my 'docker install'?
If so I can calibrate the camera that's currently used by docker using the normal install - then transfer 'whatever'...

**Comment by aaronwmorris** [comment]
Its not impossible to do that, but you would have to run the dark frame import script from within the container.

I am working on the dark frame container stuff now.  I should have it ready in a few hours.

**Comment by aaronwmorris** [comment]
Merged #1061 to support dark frame capture in containers.

There are a few more `.env` variables to add.  You should just have to rebuild your capture container to add the functionality.  Hopefully, it does not require a full image rebuild, but one of the other changes I added may force it.

```
docker compose build capture.indi.allsky
```

Note:  I also incremented indi to v2.0.5 in the defaults, but you do not need to upgrade for libcamera to function.

**Comment by warwound** [comment]
OK, I've rebuilt everything and am now wondering 'where is the new calibrate within docker' option?
Is it a command line option and I need to use docker exec to create a shell?
I don't see any new option for this in the web interface.

**Comment by aaronwmorris** [comment]
The option to capture darks is in your `.env` file.  There are 4 new variables that need to be defined there.

**Comment by warwound** [comment]
Thanks again for all your help, I'm now waiting for some clear skies here in the UK to give everything a proper test.
I'll mark this issue as now closed.
