### ISSUE TITLE
Moon Mode - unable to reactivate, duplication in config?

### ISSUE THREAD

**Issue by StarGeezerPhil** [aaronwmorris/indi-allsky#1114]
I previously had Moon Mode disabled (altitude set to 91).

Now, I'm trying to enable Moon Mode, but find there are two different places to set the _Moon Mode Altitude_ and _Phase_ - under the **Processing** and **Location** tabs.

I've set both of these to a low value: 1 degrees and phase: 33%, but it doesn't seem to enable.

Have rebooted the Pi a few times and also updated to the latest version with no success.

**Comment by aaronwmorris** [comment]
The setting on processing only affects Star Trail processing.

What are you using to base if moon mode is enabled or disabled?

**Comment by StarGeezerPhil** [comment]
Ha, sorry @aaronwmorris - didn't it used to say "Moon Mode" down in the bottom-left corner.

I've just checked the log and it is using the correct gain setting. Sorry about this (hangs head in shame)

**Comment by aaronwmorris** [comment]
Not that I recall, but I have been known to forget things.  I can look into implementing this.
