### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by Durandale69** [aaronwmorris/indi-allsky#1125]
Hello,
I've just installed Indi-allsky. I don't know why I can't connect with my credentials :-(
I can't figure out how to reset the password.
is there a tutorial please?
Thanks

**Comment by Durandale69** [comment]
I found it!
https://github.com/aaronwmorris/indi-allsky/wiki/Web-Interface-Password
it seems some special characters are not supported that's why my password didn't work. I change it and it's running well.🥰

**Comment by aaronwmorris** [comment]
I am glad you figured it out.  Sorry, I had to travel for work this past week.

What characters did you have a problem with and I will check it out.
