### ISSUE TITLE
Shortening Maximum Exposure in Config causes crash

### ISSUE THREAD

**Issue by gaitskell** [aaronwmorris/indi-allsky#1129]
Shortening the Maximum Exposure Time significantly in Config appears to cause significant errors in processing flow including a notification Warning that Upload worker has restart more than 10 times. No new images are being recorded.

This happens when I have auto exposure times of say 50 secs and I the. set a maximum of only 10 secs and save/reload the new config. 

 ![IMG_0724](https://github.com/aaronwmorris/indi-allsky/assets/3291536/2f0979b6-2389-4050-883d-b97ca06fb74d)

**Comment by aaronwmorris** [comment]
The error related to the Upload Worker is a red-herring.  Nothing related to the exposure would affect that.  There should be exceptions in the log related to the upload worker in `/var/log/indi-allsky/indi-allsky.log`.

If there were problems related to the exposure, those should be in the log as well.  Do you have a screenshot of your exposure settings?

Sorry for not getting back sooner, I have been traveling for the past week for work.
