### ISSUE TITLE
Upgrade of Indi-Allsky broke webapp

### ISSUE THREAD

**Issue by jshall77** [aaronwmorris/indi-allsky#1191]
Hello,
I recently updated my RPi4 instance of indi-allsky using the instructions [here](https://github.com/aaronwmorris/indi-allsky/wiki/Updating-indi-allsky)

After pulling the new code and running setup.sh, the installer fails with the below message.  I have tried doing a full rebuild via build_indi.sh, but the app still fails with the below.  Any assistance would be appreciated, hopefully I don't have to get back on the roof to reflash the SD card.

_The following NEW packages will be installed:
  rpicam-apps
0 upgraded, 1 newly installed, 0 to remove and 8 not upgraded.
Need to get 0 B/318 kB of archives.
After this operation, 1,799 kB of additional disk space will be used.
(Reading database ... 121466 files and directories currently installed.)
Preparing to unpack .../rpicam-apps_1.4.3-1_arm64.deb ...
Unpacking rpicam-apps (1.4.3-1) ...
dpkg: error processing archive /var/cache/apt/archives/rpicam-apps_1.4.3-1_arm64.deb (--unpack):
 trying to overwrite '/usr/bin/camera-bug-report', which is also in package libcamera-apps-lite 1.2.1-1+bookworm+1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/rpicam-apps_1.4.3-1_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

###############
###############

The setup script exited abnormally, please try to run again..._

Thanks,
Jeff

**Comment by aaronwmorris** [comment]
Try removing `libcamera-apps-lite` and re-run setup.

```
sudo apt-get remove libcamera-apps-lite
```
