### ISSUE TITLE
Update Database conversion Wiki page with instructions to enable virtualenv

### ISSUE THREAD

**Issue by degan6** [aaronwmorris/indi-allsky#1208]
The Database conversion page is very helpful, but I ran into a small issue while trying to run the final steps.

The page doesn't call out that you should enable the virtualenv to run the flask commands. Here is an updated code block.

I was able to get it to work, but had to struggle a bit. Hoping this small change will help others.

```
  rm -f /var/lib/indi-allsky/migrations/versions/*.py
  
  # enable the virtualenv
  cd indi-allsky  #cd to the root of where you downloaded the git repo
  source virtualenv/indi-allsky/bin/activate
  
  flask db revision --autogenerate
  flask db upgrade head
  
  ./config.py bootstrap
```

**Comment by aaronwmorris** [comment]
I have updated the wiki page to include this information.  Thanks for catching this!

**Comment by degan6** [comment]
Thanks
