### ISSUE TITLE
Turn off orange highlight?

### ISSUE THREAD

**Issue by henrikeri** [aaronwmorris/indi-allsky#1210]
I've been scouring the wiki and settings, but I cannot seem to find it. Is there a way to turn off the orange-ish highlight in the over exposed areas?

![image](https://github.com/aaronwmorris/indi-allsky/assets/35510093/e505b938-0125-41d4-a5cd-fc816f833e6c)

**Comment by aaronwmorris** [comment]
Are you using the 16-bit CLAHE contrast enhancement?

**Comment by henrikeri** [comment]
Hi,

Yes I am

**Comment by aaronwmorris** [comment]
This is a bug in the 16-bit version of CLAHE.  I will get around to trying to track it down soon.  You can use the non-16bit version in the meantime.

**Comment by aaronwmorris** [comment]
I am going to close this issue to merge with #1164
