### ISSUE TITLE
Unable to Login on Web App

### ISSUE THREAD

**Issue by HxPI** [aaronwmorris/indi-allsky#1220]
I was going to use my indi-allsky device for the solar eclipse but I was unable to login to set the date/time. I was able to connect to the hotspot but when providing my credentials, it would not login and I was unable to access system settings. Has this come up before and is there anything to resolve this?

**Comment by aaronwmorris** [comment]
You may reset your password using the instructions from the wiki.

https://github.com/aaronwmorris/indi-allsky/wiki/Web-Interface-Password

**Comment by HxPI** [comment]
It's working now, I didn't do anything. Strange.
