### ISSUE TITLE
Image loop out of order

### ISSUE THREAD

**Issue by smokedsalmonbagel** [aaronwmorris/indi-allsky#1229]
Maybe I am missing something but when I click "Loop" on the left hand menu the images being played back seems to skip around quite a bit.  It will play in order ben then go the other direction and speed up / slow down etc.  The frame counter in the lower right shows the same, counting up, down etc.

**Comment by aaronwmorris** [comment]
When you first load the loop, if the images load slowly, they will appear to load out of order and skip around until all of the images are completely downloaded.

This is an unfortunate side effect of the browser.  The display of the images is asynchronous from the download of the images.  The javascript is telling the browser to show an image, the browser starts downloading the image, but the next image is shown before the first finished downloading, repeat for each image.

**Comment by smokedsalmonbagel** [comment]
Ok, that's what I suspected.  Also what is "Rock"?  Sorry if I missed this in the wiki.

**Comment by mburge** [comment]
And here I've been working on decoding ROCK as an acronym for months. Reverse Order of Capture K?!
