### ISSUE TITLE
After new install webpage will not load. Bullseye OS

### ISSUE THREAD

**Issue by Dentonknifeworks** [aaronwmorris/indi-allsky#1236]
I had to do a fresh install today using Bullseye OS and after the setup the WEBpage will not load just get not found.

**Comment by Dentonknifeworks** [comment]
Web log
Apr 24 20:29:30 ALLSKY477 gunicorn.indi_allsky.wsgi.error: [1661] Shutting down: Master
Apr 24 20:29:45 ALLSKY477 gunicorn.indi_allsky.wsgi.error: [2272] Starting gunicorn 22.0.0
Apr 24 20:29:45 ALLSKY477 gunicorn.indi_allsky.wsgi.error: [2272] Listening at: unix:/var/lib/indi-allsky/gunicorn-indi-allsky.sock (2272)
Apr 24 20:29:45 ALLSKY477 gunicorn.indi_allsky.wsgi.error: [2272] Using worker: gthread
Apr 24 20:29:45 ALLSKY477 gunicorn.indi_allsky.wsgi.error: [2274] Booting worker with pid: 2274

**Comment by aaronwmorris** [comment]
That error does not indicate any problems.  What URL are you navigating to for your system?  Does it include `/indi-allsky/` at the end?

**Comment by Dentonknifeworks** [comment]
https://192.168.254.178/indi-allsky/
The IP of the pi

**Comment by aaronwmorris** [comment]
Are you absolutely sure that is the correct IP of your allsky system?  I am trying to think of a reason for this behavior.

**Comment by Dentonknifeworks** [comment]
YES
At this point I am going to start all over as I have messed with this all day and want to start it fresh.

**Comment by aaronwmorris** [comment]
If you still have issues, I am more than willing to login remotely if you can setup a port forward.

**Comment by Dentonknifeworks** [comment]
Thanks,
My plan today is to clone a working copy and then switch the camera with the script in misc. I would go with bookworm but yesterday I had odd issues with the python and I need that for my dewheater code. This was my first look at bookworm so I am going to set up a pi with it and see why I had issues with python. This should work for me today.

**Comment by Dentonknifeworks** [comment]
I was able to get it running today. I will close this as a one time issue that I have no idea as to what happened. Thanks.
