### ISSUE TITLE
multi-columns bloom ccd

### ISSUE THREAD

**Issue by fcbarclo** [aaronwmorris/indi-allsky#1239]
Using Oculus Pro 180 all sky camera , on a raspberry pi 4 8gb ram, ssd disk,  and bullseye os. Latest version of indi allsky.
During day it shows multi-columns bloom on the area overexposed (it seems that there is not any setting to manage overexpose for this camera). 
This multi-columns 
![attach_1](https://github.com/aaronwmorris/indi-allsky/assets/26539791/fc62f043-da27-4ca3-83f2-ea240965e031)
increases during day , up to completely fill the image (mainly if there are clouds), like this
![attach_2](https://github.com/aaronwmorris/indi-allsky/assets/26539791/ccf1f3f5-9345-4898-93b9-79d7164ba082)
or this :
![attach_2_2](https://github.com/aaronwmorris/indi-allsky/assets/26539791/02edf5fc-cee8-4252-a366-3dd0aa2cb04e)

During night, it is fine for the most cases, but sometimes i will get image like:
![attach_3](https://github.com/aaronwmorris/indi-allsky/assets/26539791/3d96ac19-0cdd-46c2-b89f-92e4a8c0194a)

All settings relative to, min, max, default exposure are set to 0 (auto) 

Franco

**Comment by aaronwmorris** [comment]
Thank you for being patient.  I had to complete a merge for this.

If you could update the the latest code, I added a new script to explore all of the properties available for a camera.

https://github.com/aaronwmorris/indi-allsky/wiki/Updating-indi-allsky

Once updated and restarted, please report the output of the following commands:

```
./misc/support_info.sh
```

```
source virtualenv/indi-allsky/bin/active

./misc/camera_properties.py
```

**Comment by fcbarclo** [comment]
Following  is the support_info.sh output:
[support_info.txt](https://github.com/aaronwmorris/indi-allsky/files/15144231/support_info.txt)

and the output of the camera_properties.py:
[camera_properties.txt](https://github.com/aaronwmorris/indi-allsky/files/15144240/camera_properties.txt)

**Comment by aaronwmorris** [comment]
I was hoping there would be something... anything... that could be changed, but there is nothing available.  This mirrors my experience with other Starlight Xpress cameras.  They have a fixed gain and almost no options to make any other adjustments.  It is very unfortunate because the nighttime performance is quite good (with stretching).
