### ISSUE TITLE
Install/upgrade fails on photutils install

### ISSUE THREAD

**Issue by jshall77** [aaronwmorris/indi-allsky#1260]
Hello,

I currently have 2 RPi 4's running your software.  I just rebuilt one of them and during installation, I receive the following error:

Python _dependencies [photutils] failed.
The end of the file is:
Looking in indexes: https://pypi. org/simple, https://www.piwheels.org/simple
Collecting photutils
Downloading photutils-1.12.0.tar.gz (1.2 MB)
1.2/1.2 MB 2.7 MB/s eta 0:00:00
ERROR: photutils from https://files.pythonhosted. org/packages/10/b6/2ecd1ddebf269aa78103959a99ebb2c2ca9070f392cf10ac767fc4176b2a/photutils-1.12.0.tar.gz (from -r /tmp/package (li
1) ) does not appear to be a Python project: neither 'setup.py' nor 'pyproject. toml' found.

Then the installation quits.

Any help is appreciated!!

**Comment by aaronwmorris** [comment]
Are you sure you are using indi-allsky and not the other allsky software?  indi-allsky does not have a requirement for photutils.
