### ISSUE TITLE
Fix detection mask on a cropped image

### ISSUE THREAD

**Issue by aaronwmorris** [aaronwmorris/indi-allsky#1286]
Last April you made a change to  indi-allsky/flask/view.py (patch #1227) that may have fixed the requester issue but broke it for me because you forgot to crop the star detection mask and this caused the charts to not work for me.

I patched it for myself around line 1060 in view.py with

        img_crop_roi = self.indi_allsky_config.get('IMAGE_CROP_ROI', [])
        x1 = int(img_crop_roi[0])
        y1 = int(img_crop_roi[1])
        x2 = int(img_crop_roi[2])
        y2 = int(img_crop_roi[3])
        numpy_mask = numpy_mask[y1:y2,x1:x2]

**Comment by aaronwmorris** [comment]
Merged #1289

**Comment by morganjrees** [comment]
Where do I find detection mask in settings?
