### ISSUE TITLE
Raspberry CPU Temp for Fan Control

### ISSUE THREAD

**Issue by giangitesta** [aaronwmorris/indi-allsky#1310]
Hi, I need some help. I would like to use my Raspberry's CPU temperature as a target for controlling the fans. It's possible?

Regards

**Comment by aaronwmorris** [comment]
I will work on that today.

**Comment by aaronwmorris** [comment]
Merged #1311 .  For Raspberry Pi 3/4/5, the CPU temperature should be `System Temp 10`.

**Comment by aaronwmorris** [comment]
@giangitesta What kind of fan do you have connected?

**Comment by giangitesta** [comment]
Hi,
i connected a 40 mm x 10 mm 12V DC Brushless fan and two 60mm fans always at 12 V DC controlled through a logic level mosfet in ON/OFF mode.
Unfortunately, I haven't had a chance to update yet to test. I hope to do it this weekend.
Greetings and thanks for your great work.

![IMG_20240607_142311](https://github.com/aaronwmorris/indi-allsky/assets/11334251/51bc8454-014b-4940-a76f-be69912af471)
![IMG_20240607_142323](https://github.com/aaronwmorris/indi-allsky/assets/11334251/af3c8280-2bb3-47e0-a950-d47f5b677f5f)

**Comment by aaronwmorris** [comment]
Very nice!  I just wanted to make sure you were not using something like the PoE HAT with an i2c controllable fan.

**Comment by aaronwmorris** [comment]
@giangitesta I just wanted to follow up to make this was working for you.

**Comment by giangitesta** [comment]
Good morning Aaron,
sorry for the delay in replying.
You can consider the update working.
Thanks again and regards.

G
________________________________

**Comment by giangitesta** [comment]
Good morning @aaronwmorris ,
sorry for the delay in replying.
You can consider the update working.
Thanks again and regards.

G
