### ISSUE TITLE
Failing to login/load

### ISSUE THREAD

**Issue by clambert24** [aaronwmorris/indi-allsky#1315]
I'm having trouble logging into it via the ip address webpage and it just times out. However if I physically turn it off and on, it will then load as normal,  but a little time later it all fails to load. 
The strange thing is, if I load up my raspcontroller app, it can still see the pi on the network, but won't login. It's almost like it's got too much going on and can't compute an extra process to login either via webpage or VNC viewer. 
![Screenshot_20240609_093817_Samsung Internet](https://github.com/aaronwmorris/indi-allsky/assets/83610871/97a506fe-b328-43f2-b25e-c5853155e50b)

**Comment by aaronwmorris** [comment]
Are you using wifi to connect to the Pi?  If you are using wifi, it could just be temporarily losing connection.
