### ISSUE TITLE
Remove login requirement

### ISSUE THREAD

**Issue by henrikeri** [aaronwmorris/indi-allsky#1342]
Hi,

How can I remove the login requirement? I followed the upgrade instructions, and selected "No" instead of "Yes", but I am still getting the login screen when restarting the server. Is there a parameter that I have to change in some file? I'd rather not reinstall.

**Comment by aaronwmorris** [comment]
In order to complete disable all authentication, you would need to edit `/etc/indi-allsky/flask.json`

```
"LOGIN_DISABLED": true
```
