### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by pierrebilb** [aaronwmorris/indi-allsky#1357]
I try to install on orange pi 3B with debian bookworm; i get that in the terminal:
The following packages have unmet dependencies:
 libmount-dev : Depends: libblkid-dev but it is not going to be installed
                Depends: libmount1 (= 2.38.1-5+b1) but 2.38.1-5+deb12u1 is to be installed
 libxft-dev : Depends: libfontconfig1-dev
E: Unable to correct problems, you have held broken packages.

**Comment by aaronwmorris** [comment]
You may try doing a full package upgrade first and then see if it resolves.

```
sudo apt-get update

sudo apt-get dist-upgrade
```

**Comment by pierrebilb** [comment]
Hi Aaron,
still the same error:
The following packages have unmet dependencies:
 libmount-dev : Depends: libblkid-dev but it is not going to be installed
                Depends: libmount1 (= 2.38.1-5+b1) but 2.38.1-5+deb12u1 is to be installed
 libxft-dev : Depends: libfontconfig1-dev
E: Unable to correct problems, you have held broken packages.

**Comment by aaronwmorris** [comment]
Is this a 32-bit distribution or 64-bit?

**Comment by pierrebilb** [comment]
It'a 64 bit distribution; the debian image found at this page:
http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/service-and-support/Orange-Pi-3B.html
Thanks for your help!
Pierre

**Comment by pierrebilb** [comment]
I installed instead the ubuntu distribution and everything went fine! No more errors.
