### ISSUE TITLE
Annoying notifications

### ISSUE THREAD

**Issue by piratinskii** [aaronwmorris/indi-allsky#1413]
Hey! I'm not sure if this is a bug, or I just can't find way to change it. But I get notifications every time, when I reload the pages. For example: 
![image](https://github.com/user-attachments/assets/3d94d340-a14b-42f5-ad9a-d19f0730c147)
But it was already 2 hours ago and I saw this notification 20 times already. How can I change it?

**Comment by aaronwmorris** [comment]
Have you checked the logs to see why the image worker is being restarted?

**Comment by aaronwmorris** [comment]
These notifications are for the image worker which is responsible for processing and saving images.  If it is crashing, this is not a common problem and is an indication that something is wrong with the images or maybe masks.

**Comment by aaronwmorris** [comment]
@piratinskii Did you have any luck investigating this?

**Comment by piratinskii** [comment]
> These notifications are for the image worker which is responsible for processing and saving images. If it is crashing, this is not a common problem and is an indication that something is wrong with the images or maybe masks.

The problem not in the Worker. I meant any notification, for example "indiserver was reloaded" or something like this. I saw the notification, I clicked on the "cross button" but anyway I get this message every time, that I load a new page. And it works with any notification, I just can't "mark" it as read.

**Comment by aaronwmorris** [comment]
The X in the upper right just closes the notification window.  You have to click the Acknowledge button to mark the notification as read make sure the notification does not pop up again.

**Comment by piratinskii** [comment]
I tried this too, but, unfortunately, this doesn't work for me too

**Comment by aaronwmorris** [comment]
You may have multiple notifications.  I acknowledging causing exceptions in `/var/log/indi-allsky/webapp-indi-allsky.log`?

**Comment by aaronwmorris** [comment]
Let me know if there are any other notifications I need to focus on.
