### ISSUE TITLE
Duplicated cameras in dropdown?

### ISSUE THREAD

**Issue by alexdumitriu** [aaronwmorris/indi-allsky#1417]
Just a quick question - is there a way I can remove any of these cameras from the list here? The only one I actually have is the first one in the list. The moment I try to change to a different one from the list, the app crashes, so I'd like to avoid making a mistake when clicking on the cameras list, select an invalid one and then crashing the app.

![image](https://github.com/user-attachments/assets/e136fd82-36e4-4204-88b2-4e3c69849cfe)

Thanks a lot
Alex

**Comment by aaronwmorris** [comment]
You can hide cameras using SQL from the command line.

https://github.com/aaronwmorris/indi-allsky/wiki/SQL-queries

**Comment by alexdumitriu** [comment]
Amazing, thank you very much!
