### ISSUE TITLE
How to remove camera from the list?

### ISSUE THREAD

**Issue by TonAmSi** [aaronwmorris/indi-allsky#1432]
Hello everyone!
Does anyone know how to remove a camera from the list?
Best regards! Amy

<img width="204" alt="Bildschirmfoto 2024-07-29 um 00 37 16" src="https://github.com/user-attachments/assets/e2ee1002-d612-41bf-a0b9-7a3d96acbf7a">

**Comment by aaronwmorris** [comment]
It is not too difficult to do, but you may hide a camera with a flag in the database:

https://github.com/aaronwmorris/indi-allsky/wiki/SQL-queries

**Comment by aaronwmorris** [comment]
No worries, this bit of information is in a weird spot anyway.  I also added a link to the FAQ since you are the second person to ask about this in a week.
