### ISSUE TITLE
Rotating image for correct cardinal

### ISSUE THREAD

**Issue by giorgio-grag** [aaronwmorris/indi-allsky#1454]
It's not a really issue; I believe it's just a matter of configuring indi-allsky correctly. I want the cardinal points N, W, E, S to be in the correct positions, and I've tried rotating the image:
![image](https://github.com/user-attachments/assets/ea40b689-d10d-49c2-bd77-58a12851a739)
but it's not an ideal way to present it. Is there a method to rotate the cardinal points without rotating the image?

**Comment by aaronwmorris** [comment]
The cardinal directions may be rotated by adjusting the `Azimuth` of the camera on the Location tab.

You can also set the cardinal directions closer to your image circle by adjusting the `Image Circle Diameter` in the Cardinal directions settings on the Image tab.
