### ISSUE TITLE
Problem with square blocks (artifacts) in timelapse

### ISSUE THREAD

**Issue by Marchal1977** [aaronwmorris/indi-allsky#1460]
Hi,

Noticed having square blocks in all of my timelapses (see attached screenshot of timelapse)
![blocks](https://github.com/user-attachments/assets/58e5554a-14df-411b-8fa8-8d63d834bd52)

I changed the FFMPEG Bitrate from 5000K to 20000, 30000 or 40000K, but no luck.

Any idea?

Thanks Marchal

**Comment by aaronwmorris** [comment]
Do you see those artifacts when viewing the video that comes out of indi-allsky, or is it when viewing the video on Facebook or another service?

**Comment by Marchal1977** [comment]
The artifacts are already visible in indi-allsky itself, they are also visible in other players when viewed there.

**Comment by aaronwmorris** [comment]
Try adding `-level 3.1` to the ffmpeg options on the Image tab in the config.  Restart indi-allsky and try generating again.  It might help, might not.

**Comment by Marchal1977** [comment]
Going to try this, I will let you know the outcome!

**Comment by Marchal1977** [comment]
Had alot of issues with re-generating (alot of QUEUED/FAILED attempts). After a full reboot/restart I got it working with one timelapse so far. I added -level 3.1 to the ffmpeg options. Now I will to wait until it makes a timelapse of its own the next day. Will keep you updated!

**Comment by aaronwmorris** [comment]
The default settings require you to first delete the timelapse before you regenerate it again.  There is a setting on the Admin tab that allows you to directly overwrite and existing timelapse.

**Comment by Marchal1977** [comment]
Cannot find that setting on the Admin tab...

**Comment by aaronwmorris** [comment]
If its there, it would be at the top of that tab, under the expiration settings.  It was a recent update, so you may need to pull down the latest code.

**Comment by Marchal1977** [comment]
![image](https://github.com/user-attachments/assets/ad901d9b-59e5-4e49-b44c-5f12215783d8)

**Comment by aaronwmorris** [comment]
Look like I added the functionality in #1446 on August 9th.

**Comment by Marchal1977** [comment]
![image](https://github.com/user-attachments/assets/4aba59ce-f44e-4073-8f4f-6678c644c5b6)

this one?

**Comment by aaronwmorris** [comment]
Affirmative.

**Comment by aaronwmorris** [comment]
Fantastic news!  Let it run a few more days to make sure the clean result was not just a fluke.

**Comment by Marchal1977** [comment]
Still clean! Thanks!

**Comment by aaronwmorris** [comment]
Great news!  `-level 3.1` is now a default setting in indi-allsky.
