### ISSUE TITLE
residual default to asi120 after changing camera to QHY5iii715c

### ISSUE THREAD

**Issue by broz22** [aaronwmorris/indi-allsky#1495]
Aaron,
  you fixed my problem with indi-allsky not connecting to the new camera (much appreciated) so I closed the ticket. However, the web interface defaults back to the ASI120 even though I ran the change_camera script. Everything works if I manually change the camera to the new one in the drop-dowm menu at the top of the interface. Is there any way to remove the reference to the 120? Thanks,
John

**Comment by aaronwmorris** [comment]
You may hide the ASI120 entry using instructions from this page:

https://github.com/aaronwmorris/indi-allsky/wiki/SQL-queries

**Comment by broz22** [comment]
Thank you.
John
