### ISSUE TITLE
JPG or PNG not working after update Day libcamera image type

### ISSUE THREAD

**Issue by sonny486** [aaronwmorris/indi-allsky#1503]
Updated this morning and now JPG daytime image processing not working.  Shows a quarter image only.  Not the full image.

I had to revert to RAW DNG.

Will check on this some more.

**Comment by sonny486** [comment]
Got it working by adding --width --height to the libcamera options

**Comment by sonny486** [comment]
![image](https://github.com/user-attachments/assets/01cccc9e-b7a8-421a-a8a1-4b433ebd6f07)

**Comment by aaronwmorris** [comment]
That is weird...  I am currently on vacation and I will be back later this week.

**Comment by sonny486** [comment]
No worries, enjoy your time off! 

I see if I can see anything in the code.

**Comment by sonny486** [comment]
Well it ended up being the LIBCAMERA library.  It must have had an issue, I did a system update and I noticed it installed new libcamera utilities and system files.

It's working fine now with the latest update.
Closing this issue.

**Comment by aaronwmorris** [comment]
Glad you figured it out!
