### ISSUE TITLE
upgrade from indi_v2024.05.1 to indi_v2024.09.1

### ISSUE THREAD

**Issue by leforet** [aaronwmorris/indi-allsky#1510]
Hello, I followed the instructions at https://github.com/aaronwmorris/indi-allsky/wiki/Updating-indi-allsky to upgrade 

The download of the update from GitHub appears to have gone well.
pi@piCOMET:~/indi-allsky $ git pull origin main
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 30 (delta 19), reused 29 (delta 19), pack-reused 0 (from 0)
Unpacking objects: 100% (30/30), 16.94 KiB | 299.00 KiB/s, done.
From https://github.com/aaronwmorris/indi-allsky
 * branch              main       -> FETCH_HEAD
   7b19a2bc..794fc6a5  main       -> origin/main
Updating 7b19a2bc..794fc6a5
Fast-forward
 indi_allsky/camera/indi.py              |   6 +++
 indi_allsky/flask/templates/system.html |   6 +--
 indi_allsky/flask/views.py              |  15 ++++--
 misc/camera_properties.py               |  10 ++++
 misc/flush_images.py                    | 386 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 5 files changed, 416 insertions(+), 7 deletions(-)
 create mode 100755 misc/flush_images.py

Then starting the setup.sh script went well, 
The upgrade seemed to go well, except for this final stretch.

Synchronizing state of apache2.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable apache2
**** Setup HTDOCS folder ****
**** Setup image folder ****
**** Ensure user is a member of the dialout, video, i2c, spi groups ****
**** Disabling Thomas Jacquin's allsky (ignore errors) ****
**Failed to stop allsky.service: Unit allsky.service not loaded.
Failed to disable unit: Unit file allsky.service does not exist.**
**** Starting gunicorn-indi-allsky.socket
**** Update config camera interface ****
2024-09-16 17:00:50,481 [INFO] MainProcess config._load() [912]: Loading configuration from file

There appears to be a small bug or problem, when I check the website (https://192.168.XxX.75/indi-allsky/system) after restarting the service.  I see that the release is still at 
Release indi_v2024.05.1

I checked the git directory after the update and it appears to be at the latest release
pi@piCOMET:~/indi-allsky $ systemctl --user stop indi-allsky
Warning: Stopping indi-allsky.service, but it can still be activated by:
  indi-allsky.timer
pi@piCOMET:~/indi-allsky $ systemctl --user stop gunicorn-indi-allsky
Warning: Stopping gunicorn-indi-allsky.service, but it can still be activated by:
  gunicorn-indi-allsky.socket
pi@piCOMET:~/indi-allsky $ git pull origin main
From https://github.com/aaronwmorris/indi-allsky
 * branch              main       -> FETCH_HEAD
Already up to date.

I've restarted the service & rebooted the pi, with no change on the above page.

 I went to the support page. https://192.168.XxX.75/indi-allsky/support.  and couldn't find the release version in there.  This might be of relevance 
git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

git log
commit 794fc6a5a365a0ae8aea7854d4e740586df9a0c1
Merge: 7b19a2bc eeb169e2
Author: Aaron W Morris <aaron@aarmor.net>
Date:   Fri Sep 13 20:53:43 2024 -0500

    Merge pull request #1506 from aaronwmorris/dev
    
    script to flush images from CLI

indi version: 2.0.9

indi packages

**Comment by aaronwmorris** [comment]
It appears the upgrade was completely successful.  I just did not change the version text in the release.  I will put out an update shortly.

**Comment by leforet** [comment]
great, thanks for the update.

**Comment by aaronwmorris** [comment]
Updated the version string as part of #1511

**Comment by leforet** [comment]
thanks
