### ISSUE TITLE
Exposure issues notice 

### ISSUE THREAD

**Issue by AKGhost** [aaronwmorris/indi-allsky#1515]
Could not find the right info on this issue.  Getting the error 
60.0s exposure received in 0.3s. Possible camera problem.
Using the PiCamera settings and the source image is Jpg. As the source image is coming from a camera that updates every 60 seconds ish. I have tried to adjust exposure settings but either cause high system load due to short images, or get this persistent errors even though the captured image is from the camera on the same network and minimal latency in grabbing the image. Am I missing a setting to suppress these messages?  let me know if i am looking in the wrong area for this troubleshooting or if i can provide more information.

**Comment by aaronwmorris** [comment]
What type of camera are you using?

**Comment by AKGhost** [comment]
at the moment i am using Allsky from Thomas and capturing the jpg from the main capture there as i was inable to get any settings for contrast right and my image was more grainy.  is this because i am capturing the image wrong? I am trying to see how well Indi works on my "bench" before putting on my poor Pi 2 that has been a good unit so far. 
to also clarify, is a PiHQ camera that works perfect on Allsky

**Comment by AKGhost** [comment]
oh i typed wring.. pycurl mode

**Comment by aaronwmorris** [comment]
I just wanted to make sure you were using the pyCurl camera.  I probably do have a bad assumption in the notification about the exposure time and this camera, so let me take a look at the code and go fix that.

**Comment by aaronwmorris** [comment]
Merged #1517 to disable the notifications for exposure related to pycurl camera.

**Comment by aaronwmorris** [comment]
Closing this for now.  Let me know if there are any other particular notifications I can take a look at.
