### ISSUE TITLE
typo in installation / startup instructions

### ISSUE THREAD

**Issue by morrowwm** [aaronwmorris/indi-allsky#1518]
Just installed this promising software. One minor quibble: in `https://github.com/aaronwmorris/indi-allsky/wiki/Getting-Started` I think

`source virtualenv/indi-allsky/bin/activate`

should be

`source ~/indi-allsky/virtualenv/indi-allsky/bin/activate`

**Comment by aaronwmorris** [comment]
I can add some clarifications, but this assumes that the checkout is at the root of the user's home directory, which it may not be located.  This is the reason for the relative path in the source command.

**Comment by morrowwm** [comment]
Yeah, not a big deal.  I'm sure you have higher priorities.

**Comment by morrowwm** [comment]
Explanation is sufficient.

**Comment by aaronwmorris** [comment]
This is not an invalid criticism.  Activating the virtualenv has been a source of confusion.
