### ISSUE TITLE
Temperature

### ISSUE THREAD

**Issue by bsbachert** [aaronwmorris/indi-allsky#153]
Is it possible to add Fahrenheit as a temperature option, or an option to display both. 

Thanks, love the software.

Brian

**Comment by aaronwmorris** [comment]
Absolutely!  I will work on it.

**Comment by bsbachert** [comment]
Thank you Aaron.

**Comment by aaronwmorris** [comment]
I have merged #155 to support displaying temperature in Fahrenheit and Kelvin (because why not :-) )

**Comment by bsbachert** [comment]
Because you are awesome I’m thinking. 😃

Thank you so much. I’m Celsius illiterate most days.

Brian

**Comment by aaronwmorris** [comment]
Closing this for now.  Let me know if there is anything else I can do for you.

**Comment by bsbachert** [comment]
Well, now that you mention it. 😋 I like to do color for day, and gray at
night. Is there a way to incorporate that into settings? Like a gray in
night mode setting? Color in day mode setting?

Thanks for all you do. Do you have a donate link?

Brian

**Comment by aaronwmorris** [comment]
For something like theming, I would probably need some help in that area.  I am just not a very good front-end developer.  :-)

**Comment by bsbachert** [comment]
Sorry, I was meaning camera settings. I use gray scale in night mode, then
shut it off for day mode time lapses. It would be cool if it could do it
automatically.

**Comment by aaronwmorris** [comment]
Ah, I see.  Let me think about that.

**Comment by bsbachert** [comment]
Ok, thank you.

**Comment by aaronwmorris** [comment]
Merged #183 for separate night and day grayscale options.  I renamed the config variable, so you will have to setup the option again in the configuration page.

**Comment by bsbachert** [comment]
Updated the software, and switched on gray scale at night. Waited until
night mode started. I can confirm it works. Camera switched to gray scale
instantly when night mode began.

Thank you so much!!!!

**Comment by aaronwmorris** [comment]
Closing this for now.  Let me know if there is anything else I can do!

**Comment by bsbachert** [comment]
Hi Aaron,

I see you added a feature where we could add our own data via a txt file.
Would it be possible to export the SQM data to a txt file, so I could show
that data on my website?

Thanks again for you time. Where can I donate to you, and buy you a coffee
or a beer?

Thank you, for all your help.

Brian

**Comment by aaronwmorris** [comment]
Sure, all of the data is stored in the database.

**Comment by bsbachert** [comment]
Yes. That would show the number of stars, max, avg., and min jsqm correct?

**Comment by bsbachert** [comment]
![8D059401-0D9B-4236-94B2-97D0E10401EE](https://user-images.githubusercontent.com/1251375/168491236-6c050812-2d35-460f-99ec-ef4f5841865a.jpeg)

**Comment by bsbachert** [comment]
This data..

**Comment by aaronwmorris** [comment]
Cool... I will add this to my todo list

**Comment by bsbachert** [comment]
Thanks again.

**Comment by aaronwmorris** [comment]
I have merged #202 and #203 .  This functionality will upload image metadata as JSON to the remote server.

**Comment by bsbachert** [comment]
Thank you Aaron. Now I can import the data into my webpage. Yay, so happy.

Thanks again.
Brian

**Comment by bsbachert** [comment]
Hello Aaron,

Up and running. I am downloading it from my website every 10 seconds 
using Watch, and a small wget script, then adding the json file to the 
add text option in the config dialog. Works perfect.

Thanks again.

Brian Bachert

**Comment by aaronwmorris** [comment]
Closing this issue for now.  Let me know if there is anything else I can do.

**Comment by bsbachert** [comment]
Thanks Aaron.
