### ISSUE TITLE
Database malformed

### ISSUE THREAD

**Issue by nicholasmparker** [aaronwmorris/indi-allsky#1534]
Started getting an issue last night:
Error: stepping, database disk image is malformed (11)

I tried vacuum - did not work.  Any ideas?  I can restore the DB to a backup if needed

**Comment by aaronwmorris** [comment]
The database might be toast, but try an integrity check.

```
sqlite3 /var/lib/indi-allsky/indi-allsky.sqlite "PRAGMA integrity_check;"
```

**Comment by nicholasmparker** [comment]
It's toast.  🤷

**Comment by aaronwmorris** [comment]
The DB image import is probably not working currently, I need to update some of the patterns.

I have this page for rebuilding the database:  https://github.com/aaronwmorris/indi-allsky/wiki/Rebuilding-the-database  if you do not have a recent backup.

**Comment by aaronwmorris** [comment]
I reviewed the DB image import functionality and I think it may work in its current state.  Please feel free to try it.

**Comment by aaronwmorris** [comment]
Hopefully, the database rebuilt went smoothly.  I am going to close this for now.  Please re-open if there is anything else I can do for you.

**Comment by aaronwmorris** [comment]
There were some issues at one point when I had the sqlite database pragma set to disable synchronous mode in a misguided attempt to resolve locked database problems.  Setting `synchronous=off` made things faster, but it was very prone to database corruption if there is a power loss.

This has not been the case for a while and the standard setting now is `synchronous=normal`.  Database corruption has been a very rare issue.

https://www.sqlite.org/pragma.html#pragma_synchronous

**Comment by nicholasmparker** [comment]
Got it - i will let you know on this thread if it happens again.  Im
setting up an imx462 version for my brother, so will tinker with it on
sqlite a bit to see if I can reproduce it.

**Comment by nicholasmparker** [comment]
Happened again.  I've tried two different SD cards too, so likely not the
issue.  I wonder if its an issue with the power from the raspberry POE hat
or maybe a defective raspi

**Comment by aaronwmorris** [comment]
That is very strange.  Did you have any strange error messages in the system log?

**Comment by nicholasmparker** [comment]
We can go ahead and close this out.  I had tried out two different cd cards with the same results, but switched and no problems since.  Thank you!
