### ISSUE TITLE
Add a timestamp within the MQTT payload.

### ISSUE THREAD

**Issue by giangitesta** [aaronwmorris/indi-allsky#1536]
Hi,
is it possible to add a timestamp within the published MQTT payload?
This would allow to understand if the data is up-to-date since the message is RETAINED by the broker.

Thank you very much
Regards
GT

**Comment by aaronwmorris** [comment]
Merged #1537 to include a date and time with the MQTT data.  The home assistant integration for this data is also included.

**Comment by giangitesta** [comment]
Hi @aaronwmorris,
It works. Thank you very much!
Best regard
G

**Comment by giangitesta** [comment]
Closed
