### ISSUE TITLE
Virtualenv not working

### ISSUE THREAD

**Issue by WirthmU** [aaronwmorris/indi-allsky#1544]
I am running indi-allksky on a new installation on a RPI5. When I try to tests the sensors I have on my system I enter the following command as in the wiki:
`source virtualenv/indi-allsky/bin/activate`

Then what I get is:
`-bash: virtualenv/indi-allsky/bin/activate: No such file or directory`

**Comment by aaronwmorris** [comment]
Are you in the indi-allsky git checkout folder?

**Comment by WirthmU** [comment]
I did just a regular installation as per the allsky-wiki. The webserver is up and running. I did an ssh login into the RPI as usual and entered the command:
```
as3@raspberrypi:~ $ source virtualenv/indi-allsky/bin/activate
-bash: virtualenv/indi-allsky/bin/activate: No such file or directory
```

**Comment by aaronwmorris** [comment]
You just need to be inside the indi-allsky folder before activating the virtualenv

**Comment by WirthmU** [comment]
That was it - it's working now.
Thank you!
