### ISSUE TITLE
Home Assistant Device Grouping

### ISSUE THREAD

**Issue by robbrad** [aaronwmorris/indi-allsky#1567]
Hi @aaronwmorris  - firstly amazing project here !

I want to point out if you group the HA discovery under a subtopic it will show as a device

![image](https://github.com/user-attachments/assets/547d7d11-dc95-4883-ae3f-fad88516f7ca)

See the difference in the image for astrolive otherwise it displays like this in the front end of HA 

![image](https://github.com/user-attachments/assets/f78b1a88-0ca3-4351-8420-5efbfe8668e1)

Completely up to you but it helps if the user wants to "Add a whole device to the front end"

**Comment by aaronwmorris** [comment]
Interesting, I will have to play with this option.

**Comment by aaronwmorris** [comment]
All indi-allsky entities are now placed under a unique discovery sub-topic.  This alone was not enough to group them as part of a single device.  I also had to add a `device` attribute for Home Assistant.

Merged #1569

**Comment by robbrad** [comment]
Thanks @aaronwmorris for your perseverance on this

**Comment by robbrad** [comment]
Works Great !
![image](https://github.com/user-attachments/assets/8a871dcb-0965-420d-accb-18f605a9adb6)

![image](https://github.com/user-attachments/assets/cc5b6143-fad3-4fd9-8f65-adc87b434b95)

**Comment by aaronwmorris** [comment]
Fantastic!  This has been on my to-do list for a while.  Glad it is working out for you.
