### ISSUE TITLE
Dark Calibration Frames Wiki missing a step

### ISSUE THREAD

**Issue by cgmiller76** [aaronwmorris/indi-allsky#1584]
This is minor - but it was throwing me off until I search other entries and realized I needed to perform "cd indi-allsky" before being able to generate Dark Frames.  For other new users, it might be helpful to add that step on the Wiki page instructions on creating Dark Calibration Frames.  Thanks for the work on this!

**Comment by aaronwmorris** [comment]
Thank you for the report.  I have updated the wiki to include the step of navigating to the indi-allsky folder.

**Comment by cgmiller76** [comment]
That was fast - thanks!  Happy to be able to contribute in a small way.  :)
