### ISSUE TITLE
Expire_images script does not take arguments for fits and raw images

### ISSUE THREAD

**Issue by 1im1** [aaronwmorris/indi-allsky#1588]
It looks like that the expire argument for raw and fits images is not set in the script. See lines:

https://github.com/aaronwmorris/indi-allsky/blob/4e1e0700f4034a6eff9372d701d1ddfcf30f3353/misc/expire_images.py#L332-L334

so it always uses the default (10 days)

I’m happy to open a PR is wanted.

**Comment by aaronwmorris** [comment]
Thanks for catching this.  Merged #1589 to fix.

**Comment by 1im1** [comment]
Thanks for fixing it! Awesome project.
