### ISSUE TITLE
Upgrade from 'old' allsky.git leaves 503 error

### ISSUE THREAD

**Issue by maphilli14** [aaronwmorris/indi-allsky#192]
halp!

![image](https://user-images.githubusercontent.com/6034105/167479544-4a44f1d4-3642-4dfd-9622-2f0239e7302c.png)

**Comment by maphilli14** [comment]
I did a reinstall via ./setup.sh again and it seems fixed.

**Comment by aaronwmorris** [comment]
Great!  You can review the log at `/var/log/indi-allsky/webapp-indi-allsky.log` to show the exception.
