### ISSUE TITLE
Wont run a full day. 

### ISSUE THREAD

**Issue by Dentonknifeworks** [aaronwmorris/indi-allsky#195]
The setup is a PI4 4 GB HQ, Pi Cam Running Buster
Have set up a swap file  size of 1024
Installed your softare
Installed INDI Library including all 3rd party drivers:
Set config to camera-specific settings the main one being 50% on image size.
What is happening is the Indi-all-sky shuts down. This morning the only way I could get it going was to disable the moon with 91 in the moon Altitude. Most of the time I just reboot but I am trying to figure out what the issues are.
I attached the log file

This looks to be the place that it quit

May  9 23:03:40 raspberrCAM [WARNING] ImageWorker001 image.mqtt_publish() #377: MQ publishing disabled
May  9 23:03:40 raspberrCAM [WARNING] ImageWorker001 image.upload_image() #353: Image uploading disabled
May  9 23:03:44 raspberrCAM [INFO] MainProcess allsky.run() #571: Camera last ready: 8.8s
May  9 23:03:44 raspberrCAM [INFO] MainProcess allsky.run() #572: Exposure state: OK
May  9 23:03:44 raspberrCAM [INFO] MainProcess allsky.detectNight() #800: Sun altitude: -35:08:21.1
May  9 23:03:44 raspberrCAM [INFO] MainProcess allsky.detectMoonMode() #817: Moon altitide: 42:22:15.5, phase 61.5%
May  9 23:03:44 raspberrCAM [INFO] MainProcess allsky.detectMoonMode() #821: Moon Mode conditions detected
May  9 23:03:44 raspberrCAM [WARNING] MainProcess indi.getCcdTemperature() #341: Sensor temperature: not supported
May  9 23:03:46 raspberrCAM [INFO] MainProcess indi.serverDisconnected() #175: Server disconnected (exit code = -1, localhost, 7624
May  9 23:03:47 raspberrCAM [INFO] MainProcess allsky.shoot() #994: Taking 0.66148210 s exposure (gain 16)
May  9 23:03:47 raspberrCAM [WARNING] ImageWorker001 allsky.sigterm_handler() #206: Caught TERM signal, shutting down
May  9 23:03:47 raspberrCAM [WARNING] FileUploader001 allsky.sigterm_handler() #206: Caught TERM signal, shutting down
May  9 23:03:47 raspberrCAM [WARNING] VideoWorker001 allsky.sigterm_handler() #206: Caught TERM signal, shutting down
May 10 05:25:15 raspberrCAM [INFO] MainProcess indi.__init__() #90: creating an instance of IndiClient
May 10 05:25:15 raspberrCAM [INFO] MainProcess allsky._initialize() #291: Connecting to indiserver
May 10 05:25:15 raspberrCAM [INFO] MainProcess indi.serverConnected() #172: Server connected (localhost:7624)
May 10 05:25:15 raspberrCAM [INFO] MainProcess indi.newDevice() #119: new device RPI Camera
May 10 05:25:15 raspberrCAM [INFO] MainProcess indi.newDevice() #119: new device Telescope Simulator

Help

[indi-allsky.log](https://github.com/aaronwmorris/indi-allsky/files/8661011/indi-allsky.log)

**Comment by aaronwmorris** [comment]
That is very strange.  According to the log, indi-allsky is receiving a TERM signal to shutdown which is normal when stopped from systemd.

Is it possible you had two instances of indi-allsky running simultaneously?

**Comment by Dentonknifeworks** [comment]
Well, I don't think so. I did the install fresh and then a reboot.
This morning when I found Indi not running I disabled the Moon item and then could start Indi using the web interface. It been running all day and I have got a Kellogram but not a timelapse yet. Its been about 1 hour since the transition from day to night. I do have the WEB gui up on two computers at times but cant see that doing it. I will check it in the morning and report what i find.

**Comment by Dentonknifeworks** [comment]
Ok got a timelapse. I will see if I get the night one in the morning. So Not sure why None shows up when I click on the Kellogram the timelapse opens. 
![Screen Shot 2022-05-10 at 9 41 17 PM](https://user-images.githubusercontent.com/64991600/167758367-6b0032b6-4c4d-4c60-815f-a2c1b29831ba.png)

**Comment by Dentonknifeworks** [comment]
Ok got the keg and timelapse from last night. I am going to turn on the moon mode and sell how things go.
Still not getting a thumbnail on the WEB page for timelapse
I am thinking that the thumbnail should be in the same directory as the rest.
Is this something I should see an error in the log?
Not seen a Star Trail yet but I figure that's because it's inside the office.![Screen Shot 2022-05-11 at 6 30 51 AM](https://user-images.githubusercontent.com/64991600/167840476-effb5ec3-89dc-4fb9-a85d-723e9928c0fc.png)
?

**Comment by Dentonknifeworks** [comment]
Well. it failed with moonset.  Logg attached I disabled it for today's run to see what happens.
Bra
[error.txt](https://github.com/aaronwmorris/indi-allsky/files/8677549/error.txt)
d

**Comment by Dentonknifeworks** [comment]
Larger part of the log

[error2 copy.txt](https://github.com/aaronwmorris/indi-allsky/files/8678709/error2.copy.txt)

**Comment by aaronwmorris** [comment]
Here are the key lines...

May  9 23:03:46 raspberrCAM [INFO] MainProcess indi.serverDisconnected() #175: Server disconnected (exit code = -1, localhost, 7624
May  9 23:03:47 raspberrCAM [INFO] MainProcess allsky.shoot() #994: Taking 0.66148210 s exposure (gain 16)
May  9 23:03:47 raspberrCAM [WARNING] ImageWorker001 allsky.sigterm_handler() #206: Caught TERM signal, shutting down
May  9 23:03:47 raspberrCAM [WARNING] FileUploader001 allsky.sigterm_handler() #206: Caught TERM signal, shutting down
May  9 23:03:47 raspberrCAM [WARNING] VideoWorker001 allsky.sigterm_handler() #206: Caught TERM signal, shutting down


What this tells me is something is stopping the indiserver first and then something is sending the TERM signal to indi-allsky to stop.  It looks like something on your images is stopping services.

**Comment by Dentonknifeworks** [comment]
This is a clean install with nothing else running.
I see what you are saying.
Let's see what we get tonight so far I have found turning off Moon mode works It doesn't add up.
I will entertain anything you would like me to check

**Comment by aaronwmorris** [comment]
With 4GB of RAM, it is unlikely you are running out of memory.

Just to double check, you are running vanilla Raspbian Buster (Legacy)?

**Comment by Dentonknifeworks** [comment]
pi@raspberrCAM:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@raspberrCAM:~ $

**Comment by aaronwmorris** [comment]
Is it possible your Raspberry PI is rebooting?

I tested with one of my test systems and if I kill the indiserver process, it will produce the disconnect error message.  However, in your logs, the indi-allsky process is getting the SIGTERM signal, as well.  It appears that something is stopping both services, first indiserver, then indi-allsky.  A SIGTERM signal is the default signal systemd uses to stop child processes.

**Comment by Dentonknifeworks** [comment]
Hmm, let's see where can I check that? maybe system logs?

**Comment by aaronwmorris** [comment]
If you have not manually rebooted, just check the system `uptime`

**Comment by Dentonknifeworks** [comment]
pi@raspberrCAM:~ $ uptime
 13:32:51 up 1 day,  7:05,  2 users,  load average: 1.30, 1.31, 1.13
pi@raspberrCAM:~ $

**Comment by aaronwmorris** [comment]
Keep an eye on it... if it happens again, check the uptime to see if the system rebooted.

**Comment by Dentonknifeworks** [comment]
I have done some rebooting I will not and will see if that is the case

**Comment by Dentonknifeworks** [comment]
Well, ok I have now disproven Moon mode doing it. Something is sending the Term. This log shows it doing it a lot last night. The pi did not reboot. It did take a reboot this morning to get INDI server back running.
I can redo the system but this would be the 3rd time.

**Comment by Dentonknifeworks** [comment]
[allsky.log.zip](https://github.com/aaronwmorris/indi-allsky/files/8686471/allsky.log.zip)

**Comment by aaronwmorris** [comment]
Try updating the rpi firmwares....

```
sudo rpi-update
```

**Comment by aaronwmorris** [comment]
I am going to setup my Raspi 4 with my HQ camera and re-test things for a while.

**Comment by Dentonknifeworks** [comment]
I put together a second Pi 4 2GB today I will let it run also.

**Comment by Dentonknifeworks** [comment]
rpi-update did not do it got the term again tonight.

**Comment by aaronwmorris** [comment]
My Rpi with the HQ cam ran all night without a problem.

Do you run the desktop image or the lite Raspbian image?

**Comment by Dentonknifeworks** [comment]
I run a Desktop
Mine crashed again.
The second one worked all night the same setup Desktop, Buster.
Am I running the wrong image?

**Comment by aaronwmorris** [comment]
No, you are not running the wrong image, the desktop image should be fine, I am just looking for differences.

Have you double checked the physical wiring and the camera cable?

**Comment by Dentonknifeworks** [comment]
Well yes I even switched out the ribbon cable.

**Comment by Dentonknifeworks** [comment]
Well, the second Pi is running with no issues. I put TJ's software back in the first Pi and it's running with no issues.
So we're going to run with that. Thanks for your help not sure what the issue was but looks to be a one-off. Feel free to close this.
Brad

**Comment by Dentonknifeworks** [comment]
Well, I took the second pi outside last night and got the term signal. Everything on this is different hardware. The same method of installation. 
[indi-allsky.log.zip](https://github.com/aaronwmorris/indi-allsky/files/8715861/indi-allsky.log.zip)

**Comment by aaronwmorris** [comment]
I just re-deployed my test camera using the full buster image with GUI and running as the pi user.  I will let this run for a while.

**Comment by Dentonknifeworks** [comment]
Any issues on your end?

**Comment by aaronwmorris** [comment]
My camera ran for 4 days straight until it looks like something related to the camera crashed (completely different error).

**Comment by aaronwmorris** [comment]
I just checked my test system again.... 10 days of continuous uptime.

**Comment by Dentonknifeworks** [comment]
Starting a new install today
Going to install indi driver from https://www.indilib.org/get-indi/download-rpi.html
Then your install it and see what happens.

**Comment by Dentonknifeworks** [comment]
Ran yesterday and overnight but no time-lapses.
I have the Scaling at 50 are there other settings I need to set in the Config file?

**Comment by aaronwmorris** [comment]
The only difference in my case is I normally set the scaling to 75%.

**Comment by Dentonknifeworks** [comment]
Well, 3 days no issues.
What is HUP indi-allsky?

**Comment by aaronwmorris** [comment]
That is good news!

HUP causes indi-allsky to re-read the config file and apply/change most of the settings in realtime without a full process restart.  Camera gain and bin settings will not change, but almost all of the other settings take effect immediately.

**Comment by Dentonknifeworks** [comment]
Lets close this. Thanks for the help.
