### ISSUE TITLE
Feature request: Expiry of content

### ISSUE THREAD

**Issue by ennui2342** [aaronwmorris/indi-allsky#245]
My raspberry pi is very light on storage so with my TJ setup I kept only a few days on it and primarily used the scp to push everything to a nas for long term archiving. I assumed the expire parameter in the indi-allsky config set the same behaviour, but I now realise this is for images written out and doesn't include the videos . Would it be possible to have a limit on the number of days of data stored in total? Thanks.

**Comment by aaronwmorris** [comment]
I will work on this.

**Comment by aaronwmorris** [comment]
Merged #246 to allow expiring old timelapses, keograms, and star trails.  The default age is 365 days.

**Comment by ennui2342** [comment]
Perfect, thanks for adding this - it'll tide me over until I picked up a new big SD card on prime day :)
