### ISSUE TITLE
Image expiry for fits

### ISSUE THREAD

**Issue by ennui2342** [aaronwmorris/indi-allsky#290]
Hi Aaron,

Small bug report that the image expiry and cleanup doesn't remove the saved fits images.

-Mark

**Comment by aaronwmorris** [comment]
This was an intentional oversight, so I will add some code to perform cleanup of the fits files as well as the original image files.

**Comment by aaronwmorris** [comment]
Merged #293 to expire export (raw) and fits image files.

**Comment by aaronwmorris** [comment]
Closing this issue for now.  Reopen if there are still problems with the image expirations.
