### ISSUE TITLE
opencv-python

### ISSUE THREAD

**Issue by pierrebilb** [aaronwmorris/indi-allsky#3]
Hello,on a rpi 3B with rpiOS 10, running setup.sh, building wheel for opencv-python seems to run forever..
Something missing on my config?

**Comment by aaronwmorris** [comment]
I was installing opencv-python for a different project a few days ago (on a Raspi 3) and I finally canceled it it was taking so long.

Something has changed with the module.  I will go investigate.

**Comment by aaronwmorris** [comment]
I found the cause.  There are no prebuilt wheel packages for the latest version 4.5.4.58 of opencv-python on arm.  I version locked my requirements to 5.4.3.56.  I also switched over to the opencv-python-headless package as I do not think the GUI utils are useful here.

**Comment by aaronwmorris** [comment]
Here is the page regarding the wheels:  https://www.piwheels.org/project/opencv-python-headless/

I am not even sure the package will successfully build as it says the build failed for 4.5.4.58.

**Comment by pierrebilb** [comment]
Ok,
thanks a lot. I will try tomorrow the new version of setup.sh and tell you..

**Comment by pierrebilb** [comment]
New version run fine; everything is working (qhy5lii-m)!
Thanks!!
