### ISSUE TITLE
Orb RGB

### ISSUE THREAD

**Issue by ennui2342** [aaronwmorris/indi-allsky#306]
Hi Aaron,

I've just updated to master and the orb colours seem to have reverted to BGR rather than RGB.

-Mark

**Comment by aaronwmorris** [comment]
I had all my orbs set to gray, so I did not notice that.  I'll get this fixed.

**Comment by aaronwmorris** [comment]
Merged #307 to fix the orb colors.

This bug was introduced when I added the new Orb modes for azimuth and altitude rendering in #287

**Comment by aaronwmorris** [comment]
Closing this issue for now.  Reopen if you still have an issue.
