### ISSUE TITLE
What Indi installs is required before your setup. A question

### ISSUE THREAD

**Issue by Dentonknifeworks** [aaronwmorris/indi-allsky#308]
Every time I try to install your software Indi pre-installs is a moving target.
What is required first?
RPI 4
64bit
HQ pi Cam

Thanks
Brad

**Comment by aaronwmorris** [comment]
With the latest release of indi-allsky, you can use Raspbian 11 64bit with the libcamera integration for the Rpi HQ camera (libcamera_imx477).

You will have to build indi with the `./misc/build_indi.sh` before you run the setup.sh script.

**Comment by Dentonknifeworks** [comment]
![Screen Shot 2022-08-20 at 2 57 19 PM](https://user-images.githubusercontent.com/64991600/185764132-285d2457-e7d2-4337-909b-8910f55084a9.png)
Hangs up here

**Comment by aaronwmorris** [comment]
It is probably not hung.  Compiling indi takes a while.

**Comment by Dentonknifeworks** [comment]
Well that took all most 2 hours but It completed with no errors.

**Comment by Dentonknifeworks** [comment]
This worked took a long time
