### ISSUE TITLE
Stretching images

### ISSUE THREAD

**Issue by t-ara-fan** [aaronwmorris/indi-allsky#340]
Hi,
I just started reading about indi-allsky. Nice work - it looks really good, I am installing it right now.

I have a question I could not find an answer to while scrolling through the project.  Do you have an option to automatically "stretch" images to boost contrast of features like the Milky Way?  I have dabbled with some AllSkyCamera software.  I use openCV to stretch the image, and it really boosts the Milky Way, aurora, and faint meteors.

The stretch is quite simple. A sample photo with Perseid meteor is attached. 

![20210812_223354_Gn200_+30C_60s_Gm030_L45](https://user-images.githubusercontent.com/70928835/187779059-84e8fd19-2710-4e16-af53-fb5035fcbd49.jpg)

**Comment by t-ara-fan** [comment]
Great, I got it up and running. (Off topic: after step 6 in your instructions "Login to the indi-allsky web application https://raspberrypi.local/"  it took me a couple minutes to figure out the user/password.  I was trying my "pi" user. Then I remembered I saw admin/secret somewhere and that worked.)

OK so now I have it running, and I see that you have CLAHE contrast enhancement available. Right now my camera is inside my house, and CLAHE gives an impressive contrast boost. I will try CLAHE under the stars when I get a chance.

**Comment by aaronwmorris** [comment]
The CLAHE definitely produces some interesting results.  I find that daytime contrast enhancing is pretty interesting, especially with clouds.  It is not really a proper stretching algorithm.

I am actually interested in implementing a stretching feature, but I have not been able to find a good reference to implement one.  If you can point me at some code or an example, I will see about getting it integrated.

**Comment by t-ara-fan** [comment]
Hi Aaron,
Thanks for your prompt response.  I will send you my code that does the "stretch" along with an explanation.

**Comment by aaronwmorris** [comment]
I have made some progress testing the stretching algorithms included with Astropy.
https://docs.astropy.org/en/stable/visualization/normalization.html

"Progress" insomuch as I now know how to use them... mostly.  :-)  Some of the algorithms are pretty expensive in terms of CPU.

I would still be happy to take a look at any code you would be willing to contribute.

**Comment by aaronwmorris** [comment]
Closing this issue for now.
