### ISSUE TITLE
timelapse 

### ISSUE THREAD

**Issue by dave21850** [aaronwmorris/indi-allsky#361]
bonjour a tous j'ai ce défaut qui apparait 5 2022-09-25 08:35:32 VIDÉO ÉCHEC Le dossier d'image n'existe pas : /var/www/html/allsky/images/20220925/night pouvez vous m'aider merci 
<img width="740" alt="Capture d’écran 2022-09-25 à 09 22 00" src="https://user-images.githubusercontent.com/41945526/192132801-f7e339ec-67a4-407e-858b-fe354f9d0b02.png">

**Comment by aaronwmorris** [comment]
I think you tried to generate the video too early since there were no night time images yet for 2022-09-25 (today)

**Comment by aaronwmorris** [comment]
This may not be clear, but the date for a night time timelapse is always the date at the start of the night (not the end of the night).

**Comment by dave21850** [comment]
MERCI POUR VOS REPONSE MAIS LA CREATION DU TIMELAPSE NE MARCHE TOUJOURS PAS 
<img width="1156" alt="Capture d’écran 2022-09-26 à 12 02 41" src="https://user-images.githubusercontent.com/41945526/192249551-3928be13-ae43-4088-b979-b05d694ee7d6.png">
<img width="1156" alt="Capture d’écran 2022-09-26 à 12 05 41" src="https://user-images.githubusercontent.com/41945526/192250109-e295657f-2fde-4313-8236-b04ab8e44f57.png">
<img width="1156" alt="Capture d’écran 2022-09-26 à 12 05 22" src="https://user-images.githubusercontent.com/41945526/192250114-00bd953b-7613-4d17-9fa9-d0df779995a6.png">

**Comment by aaronwmorris** [comment]
If you are using the Raspi HQ camera (IMX477) or the IMX378, you probably need to enable the FFMPEG Scaling option to make the resulting video smaller.

![image](https://user-images.githubusercontent.com/17464290/192283815-d8388049-7676-42a3-912f-69fb953edaf9.png)

Once you enable that, delete the existing keogram/startrails and and try to regenerate.

**Comment by dave21850** [comment]
j'ai changé les paramètres mais toujours pas de timelapse !
<img width="1156" alt="Capture d’écran 2022-09-26 à 16 24 05" src="https://user-images.githubusercontent.com/41945526/192301852-435f4735-00d1-4ddd-a617-d1a00212fef7.png">
<img width="1156" alt="Capture d’écran 2022-09-26 à 16 25 48" src="https://user-images.githubusercontent.com/41945526/192302003-b4e15ea1-adc2-4bc2-bfdd-f890c5974e8c.png">

**Comment by aaronwmorris** [comment]
Make sure you "Reload" the configuration or just restart your raspberry pi after to change the config options.  The options are not changed until you reload the config.

**Comment by dave21850** [comment]
bonsoir c'est ce que j'ai fait mais toujours rien désolé

**Comment by aaronwmorris** [comment]
You will have to look at the logs at `/var/log/indi-allsky/indi-allsky.log` and look for error messages.

What type of Raspberry Pi do you have?

**Comment by dave21850** [comment]
UN Raspberry Pi  4 2 G RAM

**Comment by dave21850** [comment]
Sep 27 07:03:23 raspberrypi [WARNING] ImageWorker003 image.calibrate() #880: Temperature matched bad pixel map not found: -273.15c
Sep 27 07:03:23 raspberrypi [WARNING] ImageWorker003 image.calibrate() #898: Bad Pixel Map not found: ccd1 16bit 4.6067233s gain 1 bin 1 -273.15c
Sep 27 07:03:23 raspberrypi [INFO] ImageWorker003 image.calibrate() #910: Searching for dark frame: gain 1, exposure >= 4.6, temp >= -273.1c
Sep 27 07:03:23 raspberrypi [WARNING] ImageWorker003 image.calibrate() #927: Temperature matched dark not found: -273.15c
Sep 27 07:03:23 raspberrypi [WARNING] ImageWorker003 image.calibrate() #945: Dark not found: ccd1 16bit 4.6067233s gain 1 bin 1 -273.15c

**Comment by aaronwmorris** [comment]
After trying to generate a timelapse, see if you have any out of memory (OOM) messages in the system log using `sudo dmesg`.

2GB of RAM may not be enough memory to generate a 4056×2304 timelapse.  I may have to add another smaller resolution for your situation.

**Comment by dave21850** [comment]
merci pour votre aide pouvez faire une plus petite résolution ?

**Comment by aaronwmorris** [comment]
Not a problem.  I merged #363 with two additional down-scaling options.

**Comment by dave21850** [comment]
SUPER CA MARCHE MERCI BEAUCOUP POUR VOTRE AIDE !!!!!!

**Comment by aaronwmorris** [comment]
Closing this issue for now.  Let me know if I can help again!
