### ISSUE TITLE
Request: support for SVBONY SV905c Please.

### ISSUE THREAD

**Issue by pimmoon** [aaronwmorris/indi-allsky#372]
Hello,

I just recently purchased the SV905c and I would like to request for support please.

Thank you.

**Comment by aaronwmorris** [comment]
The SV905c should work with the `indi_sv305_ccd` driver.  Let me know if that does not work.

**Comment by pimmoon** [comment]
Hi, Yes, I installed choosing indi_sv305_ccd. But, It does not work.

**Comment by pimmoon** [comment]
Hi Arron,

It does work now for SV905c this time with INDI-Allsky. So it's no issue. Maybe during the first couple of tries, something may not be completed due to the fact that it is a fresh set up.

Thank you anyway.  Right now I'm playing with the settings.

Please close this issue if you would like :)
