### ISSUE TITLE
setup not working

### ISSUE THREAD

**Issue by sharpie78** [aaronwmorris/indi-allsky#382]
Hi Aaron, I've just changed the sd card in my rPi4 (4GB) to a 32GB one so I'm reinstalling indi-allsky and coming up with a problem...
setup of indi using build_indi.sh script went fine, no dependancy issues etc.
running setup.sh works fine all the way through to just after selecting a camera driver. 
here is a copy and paste from the terminal....

 8) indi_ffmv_ccd          19) indi_omegonprocam_ccd  30) indi_sx_ccd
 9) indi_fishcamp_ccd      20) indi_orion_ssg3_ccd    31) indi_toupcam_ccd
10) indi_fli_ccd           21) indi_pentax_ccd        32) indi_v4l2_ccd
11) indi_fuji_ccd          22) indi_playerone_ccd     33) indi_webcam_ccd
Select an INDI driver: 3

**** Setting up indiserver service ****
**** Setting up indi-allsky service ****
**** Setting up gunicorn ****
**** Enabling services ****
**** Setup policy kit permissions ****
**** Ensure user is a member of the systemd-journal group ****
**** Setup rsyslog logging ****
**** Indi-allsky config ****
malformed JSON string, neither array, object, number, string or atom, at character offset 2492 (before "True,\n    "STARTRAI...") at /usr/bin/json_pp line 59.

The script exited abnormally, please try to run again...

I have no idea on this one.... had a look at /usr/bin/json_pp but don't know what I'm looking for to be honest.

Can you help please ? 
Cheers
Jack

**Comment by sharpie78** [comment]
for clarification.... installed indi-allsky in Raspberry Pi OS lite (64 bit) installed on a Rapsberry Pi 4 (4GB)
clean install. nothing else done to rPi apart from updates after install of OS, NFS setup and user name changed

**Comment by aaronwmorris** [comment]
Sorry, my fault.  Merged #384 to fix the typo in the template config.

**Comment by sharpie78** [comment]
Don't worry...sussed it. I remembered from when you were helping with the Altair 224C issue. Now pulled down the files from Github and it hs completed setup. Thank-you :-)

**Comment by sharpie78** [comment]
You can close this issue off now mate. All good and working as expected.
