### ISSUE TITLE
 pyindi-client - can't build 

### ISSUE THREAD

**Issue by jkoenig72** [aaronwmorris/indi-allsky#424]
Hi,

just run the installer on a new checkout fresh from the repo. 

Distribution: Ubuntu
Release: 22.04
Arch: x86_64

INDI_DRIVER_PATH: /usr/bin
INDISERVER_SERVICE_NAME: indiserver
ALLSKY_SERVICE_NAME: indi-allsky
GUNICORN_SERVICE_NAME: gunicorn-indi-allsky
ALLSKY_ETC: /etc/indi-allsky
HTDOCS_FOLDER: /var/www/html/allsky
DB_FOLDER: /var/lib/indi-allsky
DB_FILE: /var/lib/indi-allsky/indi-allsky.sqlite
INSTALL_INDI: true
HTTP_PORT: 80
HTTPS_PORT: 443

Building wheels for collected packages: pyindi-client, pycurl, pygifsicle, inotify, dbus-python, paho-mqtt, astroscrappy, support_developer
  Building wheel for pyindi-client (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [760 lines of output]
      /home/ubuntu/indi-allsky/virtualenv/indi-allsky/lib/python3.10/site-packages/setuptools/dist.py:530: UserWarning: Normalizing 'v1.9.1' to '1.9.1'
        warnings.warn(tmpl.format(**locals()))
      running bdist_wheel
      running build
      running build_ext
      building '_PyIndi' extension
      swigging indiclientpython.i to indiclientpython_wrap.cpp
      swig -python -v -Wall -c++ -threads -I/usr/include -I/usr/include/libindi -I/usr/local/include/libindi -o indiclientpython_wrap.cpp indiclientpython.i
      Language subdirectory: python
      Search paths:
         ./
         /usr/include/
         /usr/include/libindi/
         /usr/local/include/libindi/
         ./swig_lib/python/
         /usr/share/swig4.0/python/
         ./swig_lib/
         /usr/share/swig4.0/
      Preprocessing...
      Starting language-specific parse...
      /usr/include/libindi/indiwidgettraits.h:38: Warning 325: Nested struct not currently supported (UpdateArgs ignored)
      /usr/include/libindi/indiwidgettraits.h:49: Warning 325: Nested struct not currently supported (UpdateArgs ignored)
      /usr/include/libindi/indiwidgettraits.h:60: Warning 325: Nested struct not currently supported (UpdateArgs ignored)
      /usr/include/libindi/indiwidgettraits.h:69: Warning 325: Nested struct not currently supported (UpdateArgs ignored)
      /usr/include/libindi/indiwidgettraits.h:83: Warning 325: Nested struct not currently supported (UpdateArgs ignored)
      /usr/include/libindi/indipropertyview.h:257: Warning 302: Identifier 'fill' redefined (ignored),
      /usr/include/libindi/indipropertyview.h:251: Warning 302: previous definition of 'fill'.
      /usr/include/libindi/indipropertyview.h:275: Warning 302: Identifier 'fill' redefined (ignored),
      /usr/include/libindi/indipropertyview.h:251: Warning 302: previous definition of 'fill'.
      /usr/include/libindi/indipropertyview.h:354: Warning 362: operator= ignored
      /usr/include/libindi/indipropertyview.h:359: Warning 362: operator= ignored
      /usr/include/libindi/indipropertyview.h:486: Warning 362: operator= ignored
      /usr/include/libindi/indipropertyview.h:491: Warning 362: operator= ignored
      /usr/include/libindi/indipropertyview.h:650: Warning 362: operator= ignored
      /usr/include/libindi/indipropertyview.h:655: Warning 362: operator= ignored
      /usr/include/libindi/indipropertyview.h:779: Warning 362: operator= ignored
      /usr/include/libindi/indipropertyview.h:784: Warning 362: operator= ignored
      /usr/include/libindi/indipropertyview.h:908: Warning 362: operator= ignored
      /usr/include/libindi/indipropertyview.h:913: Warning 362: operator= ignored
      /usr/include/libindi/indipropertybasic.h:116: Warning 389: operator[] ignored (consider using %extend)
      /usr/include/libindi/indipropertyswitch.h:39: Warning 325: Nested struct not currently supported (NewValues ignored)
      indiclientpython.i:181: Warning 326: Deprecated %extend name used - the struct name '_IBLOB' should be used instead of the typedef name 'IBLOB'.
      /usr/include/libindi/indiproperties.h:61: Warning 389: operator[] ignored (consider using %extend)
      /usr/include/libindi/indiproperties.h:62: Warning 389: operator[] ignored (consider using %extend)
      /usr/include/libindi/indipropertyview.h:1: Warning 401: Nothing known about base class 'WidgetTraits< _IText >::PropertyType'. Ignored.
      /usr/include/libindi/indipropertyview.h:1: Warning 401: Maybe you forgot to instantiate 'WidgetTraits< _IText >::PropertyType' using %template.
      /usr/include/libindi/indipropertyview.h:1: Warning 401: Nothing known about base class 'WidgetTraits< _INumber >::PropertyType'. Ignored.
      /usr/include/libindi/indipropertyview.h:1: Warning 401: Maybe you forgot to instantiate 'WidgetTraits< _INumber >::PropertyType' using %template.
      /usr/include/libindi/indipropertyview.h:1: Warning 401: Nothing known about base class 'WidgetTraits< _ISwitch >::PropertyType'. Ignored.
      /usr/include/libindi/indipropertyview.h:1: Warning 401: Maybe you forgot to instantiate 'WidgetTraits< _ISwitch >::PropertyType' using %template.
      /usr/include/libindi/indipropertyview.h:1: Warning 401: Nothing known about base class 'WidgetTraits< _ILight >::PropertyType'. Ignored.
      /usr/include/libindi/indipropertyview.h:1: Warning 401: Maybe you forgot to instantiate 'WidgetTraits< _ILight >::PropertyType' using %template.
      /usr/include/libindi/indipropertyview.h:1: Warning 401: Nothing known about base class 'WidgetTraits< _IBLOB >::PropertyType'. Ignored.
      /usr/include/libindi/indipropertyview.h:1: Warning 401: Maybe you forgot to instantiate 'WidgetTraits< _IBLOB >::PropertyType' using %template.
      /usr/include/libindi/indiproperty.h:61: Warning 508: Declaration of 'setProperty' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:61: Warning 508: previous declaration of 'setProperty'.
      /usr/include/libindi/indiproperty.h:62: Warning 508: Declaration of 'setType' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:62: Warning 508: previous declaration of 'setType'.
      /usr/include/libindi/indiproperty.h:63: Warning 508: Declaration of 'setRegistered' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:63: Warning 508: previous declaration of 'setRegistered'.
      /usr/include/libindi/indiproperty.h:64: Warning 508: Declaration of 'setDynamic' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:64: Warning 508: previous declaration of 'setDynamic'.
      /usr/include/libindi/indiproperty.h:65: Warning 508: Declaration of 'setBaseDevice' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:65: Warning 508: previous declaration of 'setBaseDevice'.
      /usr/include/libindi/indiproperty.h:68: Warning 508: Declaration of 'getProperty' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:68: Warning 508: previous declaration of 'getProperty'.
      /usr/include/libindi/indiproperty.h:69: Warning 508: Declaration of 'getType' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:69: Warning 508: previous declaration of 'getType'.
      /usr/include/libindi/indiproperty.h:70: Warning 508: Declaration of 'getTypeAsString' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:70: Warning 508: previous declaration of 'getTypeAsString'.
      /usr/include/libindi/indiproperty.h:71: Warning 508: Declaration of 'getRegistered' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:71: Warning 508: previous declaration of 'getRegistered'.
      /usr/include/libindi/indiproperty.h:72: Warning 508: Declaration of 'isDynamic' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:72: Warning 508: previous declaration of 'isDynamic'.
      /usr/include/libindi/indiproperty.h:73: Warning 508: Declaration of 'getBaseDevice' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:73: Warning 508: previous declaration of 'getBaseDevice'.
      /usr/include/libindi/indiproperty.h:76: Warning 508: Declaration of 'setName' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:76: Warning 508: previous declaration of 'setName'.
      /usr/include/libindi/indiproperty.h:77: Warning 508: Declaration of 'setLabel' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:77: Warning 508: previous declaration of 'setLabel'.
      /usr/include/libindi/indiproperty.h:78: Warning 508: Declaration of 'setGroupName' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:78: Warning 508: previous declaration of 'setGroupName'.
      /usr/include/libindi/indiproperty.h:79: Warning 508: Declaration of 'setDeviceName' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:79: Warning 508: previous declaration of 'setDeviceName'.
      /usr/include/libindi/indiproperty.h:80: Warning 508: Declaration of 'setTimestamp' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:80: Warning 508: previous declaration of 'setTimestamp'.
      /usr/include/libindi/indiproperty.h:81: Warning 508: Declaration of 'setState' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:81: Warning 508: previous declaration of 'setState'.
      /usr/include/libindi/indiproperty.h:82: Warning 508: Declaration of 'setPermission' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:82: Warning 508: previous declaration of 'setPermission'.
      /usr/include/libindi/indiproperty.h:83: Warning 508: Declaration of 'setTimeout' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:83: Warning 508: previous declaration of 'setTimeout'.
      /usr/include/libindi/indiproperty.h:86: Warning 508: Declaration of 'getName' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:86: Warning 508: previous declaration of 'getName'.
      /usr/include/libindi/indiproperty.h:87: Warning 508: Declaration of 'getLabel' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:87: Warning 508: previous declaration of 'getLabel'.
      /usr/include/libindi/indiproperty.h:88: Warning 508: Declaration of 'getGroupName' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:88: Warning 508: previous declaration of 'getGroupName'.
      /usr/include/libindi/indiproperty.h:89: Warning 508: Declaration of 'getDeviceName' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:89: Warning 508: previous declaration of 'getDeviceName'.
      /usr/include/libindi/indiproperty.h:90: Warning 508: Declaration of 'getTimestamp' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:90: Warning 508: previous declaration of 'getTimestamp'.
      /usr/include/libindi/indiproperty.h:91: Warning 508: Declaration of 'getState' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:91: Warning 508: previous declaration of 'getState'.
      /usr/include/libindi/indiproperty.h:92: Warning 508: Declaration of 'getStateAsString' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:92: Warning 508: previous declaration of 'getStateAsString'.
      /usr/include/libindi/indiproperty.h:93: Warning 508: Declaration of 'getPermission' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:93: Warning 508: previous declaration of 'getPermission'.
      /usr/include/libindi/indiproperty.h:96: Warning 508: Declaration of 'isEmpty' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:96: Warning 508: previous declaration of 'isEmpty'.
      /usr/include/libindi/indiproperty.h:97: Warning 508: Declaration of 'isValid' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:97: Warning 508: previous declaration of 'isValid'.
      /usr/include/libindi/indiproperty.h:99: Warning 508: Declaration of 'isNameMatch' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:99: Warning 508: previous declaration of 'isNameMatch'.
      /usr/include/libindi/indiproperty.h:99: Warning 508: Declaration of 'isNameMatch' shadows declaration accessible via operator->(),
      /usr/include/libindi/indiproperty.h:100: Warning 508: previous declaration of 'isNameMatch'.
      /usr/include/libindi/indiproperty.h:102: Warning 508: Declaration of 'isLabelMatch' shadows declaration accessible via operator->(),

...

     /usr/include/libindi/indiproperty.h:147: Warning 503: Can't wrap 'operator INDI::PropertyView<ISwitch>*' unless renamed to a valid identifier.
      /usr/include/libindi/indiproperty.h:148: Warning 503: Can't wrap 'operator INDI::PropertyView<ILight>*' unless renamed to a valid identifier.
      /usr/include/libindi/indiproperty.h:149: Warning 503: Can't wrap 'operator INDI::PropertyView<IBLOB>*' unless renamed to a valid identifier.
      /usr/include/libindi/indipropertybasic.h:112: Warning 509: Overloaded method INDI::PropertyBasic< IText >::push(INDI::WidgetView< _IText > const &) effectively ignored,
      /usr/include/libindi/indipropertybasic.h:111: Warning 509: as it is shadowed by INDI::PropertyBasic< IText >::push(INDI::WidgetView< _IText > &&).
      /usr/include/libindi/indipropertybasic.h:121: Warning 512: Overloaded method INDI::PropertyBasic< IText >::begin() const ignored,
      /usr/include/libindi/indipropertybasic.h:119: Warning 512: using non-const method INDI::PropertyBasic< IText >::begin() instead.
      /usr/include/libindi/indipropertybasic.h:122: Warning 512: Overloaded method INDI::PropertyBasic< IText >::end() const ignored,
      /usr/include/libindi/indipropertybasic.h:120: Warning 512: using non-const method INDI::PropertyBasic< IText >::end() instead.
      /usr/include/libindi/indipropertyview.h:168: Error: 'PropertyBasicText_getPermissionAsString' is multiply defined in the generated target language module.
      /usr/include/libindi/indipropertybasic.h:70: Error: Previous declaration of 'PropertyBasicText_getPermissionAsString'
      /usr/include/libindi/indipropertyview.h:176: Error: 'PropertyBasicText_getTimeout' is multiply defined in the generated target language module.
      /usr/include/libindi/indipropertybasic.h:72: Error: Previous declaration of 'PropertyBasicText_getTimeout'
      /usr/include/libindi/indipropertyview.h:198: Error: 'PropertyBasicText_findWidgetByName' is multiply defined in the generated target language module.
      /usr/include/libindi/indipropertybasic.h:137: Error: Previous declaration of 'PropertyBasicText_findWidgetByName'
      /usr/include/libindi/indipropertyview.h:315: Error: 'PropertyBasicText_at' is multiply defined in the generated target language module.
      /usr/include/libindi/indipropertybasic.h:114: Error: Previous declaration of 'PropertyBasicText_at'
      indiclientpython.i:71: Error: 'PropertyBasicText___getitem__' is multiply defined in the generated target language module.
      indiclientpython.i:109: Error: Previous declaration of 'PropertyBasicText___getitem__'
      indiclientpython.i:75: Error: 'PropertyBasicText___len__' is multiply defined in the generated target language module.
      indiclientpython.i:113: Error: Previous declaration of 'PropertyBasicText___len__'
      /usr/include/libindi/indipropertybasic.h:112: Warning 509: Overloaded method INDI::PropertyBasic< INumber >::push(INDI::WidgetView< _INumber > const &) effectively ignored,
      /usr/include/libindi/indipropertybasic.h:111: Warning 509: as it is shadowed by INDI::PropertyBasic< INumber >::push(INDI::WidgetView< _INumber > &&).
      /usr/include/libindi/indipropertybasic.h:121: Warning 512: Overloaded method INDI::PropertyBasic< INumber >::begin() const ignored,
      /usr/include/libindi/indipropertybasic.h:119: Warning 512: using non-const method INDI::PropertyBasic< INumber >::begin() instead.
      /usr/include/libindi/indipropertybasic.h:122: Warning 512: Overloaded method INDI::PropertyBasic< INumber >::end() const ignored,
      /usr/include/libindi/indipropertybasic.h:120: Warning 512: using non-const method INDI::PropertyBasic< INumber >::end() instead.
      /usr/include/libindi/indipropertyview.h:168: Error: 'PropertyBasicNumber_getPermissionAsString' is multiply defined in the generated target language module.
      /usr/include/libindi/indipropertybasic.h:70: Error: Previous declaration of 'PropertyBasicNumber_getPermissionAsString'
      /usr/include/libindi/indipropertyview.h:176: Error: 'PropertyBasicNumber_getTimeout' is multiply defined in the generated target language module.
      /usr/include/libindi/indipropertybasic.h:72: Error: Previous declaration of 'PropertyBasicNumber_getTimeout'
      /usr/include/libindi/indipropertyview.h:198: Error: 'PropertyBasicNumber_findWidgetByName' is multiply defined in the generated target language module.
      /usr/include/libindi/indipropertybasic.h:137: Error: Previous declaration of 'PropertyBasicNumber_findWidgetByName'
      /usr/include/libindi/indipropertyview.h:315: Error: 'PropertyBasicNumber_at' is multiply defined in the generated target language module.
      /usr/include/libindi/indipropertybasic.h:114: Error: Previous declaration of 'PropertyBasicNumber_at'
      indiclientpython.i:71: Error: 'PropertyBasicNumber___getitem__' is multiply defined in the generated target language module.
      indiclientpython.i:109: Error: Previous declaration of 'PropertyBasicNumber___getitem__'
      indiclientpython.i:75: Error: 'PropertyBasicNumber___len__' is multiply defined in the generated target language module.
      indiclientpython.i:113: Error: Previous declaration of 'PropertyBasicNumber___len__'
      /usr/include/libindi/indipropertybasic.h:112: Warning 509: Overloaded method INDI::PropertyBasic< ISwitch >::push(INDI::WidgetView< _ISwitch > const &) effectively ignored,
      /usr/include/libindi/indipropertybasic.h:111: Warning 509: as it is shadowed by INDI::PropertyBasic< ISwitch >::push(INDI::WidgetView< _ISwitch > &&).
      /usr/include/libindi/indipropertybasic.h:121: Warning 512: Overloaded method INDI::PropertyBasic< ISwitch >::begin() const ignored,
      /usr/include/libindi/indipropertybasic.h:119: Warning 512: using non-const method INDI::PropertyBasic< ISwitch >::begin() instead.
      /usr/include/libindi/indipropertybasic.h:122: Warning 512: Overloaded method INDI::PropertyBasic< ISwitch >::end() const ignored,
      /usr/include/libindi/indipropertybasic.h:120: Warning 512: using non-const method INDI::PropertyBasic< ISwitch >::end() instead.
      /usr/include/libindi/indipropertyview.h:168: Error: 'PropertyBasicSwitch_getPermissionAsString' is multiply defined in the generated target language module.
      /usr/include/libindi/indipropertybasic.h:70: Error: Previous declaration of 'PropertyBasicSwitch_getPermissionAsString'
      /usr/include/libindi/indipropertyview.h:176: Error: 'PropertyBasicSwitch_getTimeout' is multiply defined in the generated target language module.
      /usr/include/libindi/indipropertybasic.h:72: Error: Previous declaration of 'PropertyBasicSwitch_getTimeout'
      /usr/include/libindi/indipropertyview.h:198: Error: 'PropertyBasicSwitch_findWidgetByName' is multiply defined in the generated target language module.
      /usr/include/libindi/indipropertybasic.h:137: Error: Previous declaration of 'PropertyBasicSwitch_findWidgetByName'
      /usr/include/libindi/indipropertyview.h:315: Error: 'PropertyBasicSwitch_at' is multiply defined in the generated target language module.
      /usr/include/libindi/indipropertybasic.h:114: Error: Previous declaration of 'PropertyBasicSwitch_at'
      indiclientpython.i:71: Error: 'PropertyBasicSwitch___getitem__' is multiply defined in the generated target language module.
      indiclientpython.i:109: Error: Previous declaration of 'PropertyBasicSwitch___getitem__'
      indiclientpython.i:75: Error: 'PropertyBasicSwitch___len__' is multiply defined in the generated target language module.
      indiclientpython.i:113: Error: Previous declaration of 'PropertyBasicSwitch___len__'
      /usr/include/libindi/indipropertybasic.h:112: Warning 509: Overloaded method INDI::PropertyBasic< ILight >::push(INDI::WidgetView< _ILight > const &) effectively ignored,
      /usr/include/libindi/indipropertybasic.h:111: Warning 509: as it is shadowed by INDI::PropertyBasic< ILight >::push(INDI::WidgetView< _ILight > &&).
      /usr/include/libindi/indipropertybasic.h:121: Warning 512: Overloaded method INDI::PropertyBasic< ILight >::begin() const ignored,
      /usr/include/libindi/indipropertybasic.h:119: Warning 512: using non-const method INDI::PropertyBasic< ILight >::begin() instead.
      /usr/include/libindi/indipropertybasic.h:122: Warning 512: Overloaded method INDI::PropertyBasic< ILight >::end() const ignored,
      /usr/include/libindi/indipropertybasic.h:120: Warning 512: using non-const method INDI::PropertyBasic< ILight >::end() instead.
      /usr/include/libindi/indipropertyview.h:168: Error: 'PropertyBasicLight_getPermissionAsString' is multiply defined in the generated target language module.
      /usr/include/libindi/indipropertybasic.h:70: Error: Previous declaration of 'PropertyBasicLight_getPermissionAsString'
      /usr/include/libindi/indipropertyview.h:176: Error: 'PropertyBasicLight_getTimeout' is multiply defined in the generated target language module.
      /usr/include/libindi/indipropertybasic.h:72: Error: Previous declaration of 'PropertyBasicLight_getTimeout'
      /usr/include/libindi/indipropertyview.h:198: Error: 'PropertyBasicLight_findWidgetByName' is multiply defined in the generated target language module.
      /usr/include/libindi/indipropertybasic.h:137: Error: Previous declaration of 'PropertyBasicLight_findWidgetByName'
      /usr/include/libindi/indipropertyview.h:315: Error: 'PropertyBasicLight_at' is multiply defined in the generated target language module.
      /usr/include/libindi/indipropertybasic.h:114: Error: Previous declaration of 'PropertyBasicLight_at'
      indiclientpython.i:71: Error: 'PropertyBasicLight___getitem__' is multiply defined in the generated target language module.
      indiclientpython.i:109: Error: Previous declaration of 'PropertyBasicLight___getitem__'
      indiclientpython.i:75: Error: 'PropertyBasicLight___len__' is multiply defined in the generated target language module.
      indiclientpython.i:113: Error: Previous declaration of 'PropertyBasicLight___len__'
      /usr/include/libindi/indipropertybasic.h:112: Warning 509: Overloaded method INDI::PropertyBasic< IBLOB >::push(INDI::WidgetView< _IBLOB > const &) effectively ignored,
      /usr/include/libindi/indipropertybasic.h:111: Warning 509: as it is shadowed by INDI::PropertyBasic< IBLOB >::push(INDI::WidgetView< _IBLOB > &&).
      /usr/include/libindi/indipropertybasic.h:121: Warning 512: Overloaded method INDI::PropertyBasic< IBLOB >::begin() const ignored,
      /usr/include/libindi/indipropertybasic.h:119: Warning 512: using non-const method INDI::PropertyBasic< IBLOB >::begin() instead.
      /usr/include/libindi/indipropertybasic.h:122: Warning 512: Overloaded method INDI::PropertyBasic< IBLOB >::end() const ignored,
      /usr/include/libindi/indipropertybasic.h:120: Warning 512: using non-const method INDI::PropertyBasic< IBLOB >::end() instead.
      /usr/include/libindi/indipropertyview.h:168: Error: 'PropertyBasicBlob_getPermissionAsString' is multiply defined in the generated target language module.
      /usr/include/libindi/indipropertybasic.h:70: Error: Previous declaration of 'PropertyBasicBlob_getPermissionAsString'
      /usr/include/libindi/indipropertyview.h:176: Error: 'PropertyBasicBlob_getTimeout' is multiply defined in the generated target language module.
      /usr/include/libindi/indipropertybasic.h:72: Error: Previous declaration of 'PropertyBasicBlob_getTimeout'
      /usr/include/libindi/indipropertyview.h:198: Error: 'PropertyBasicBlob_findWidgetByName' is multiply defined in the generated target language module.
      /usr/include/libindi/indipropertybasic.h:137: Error: Previous declaration of 'PropertyBasicBlob_findWidgetByName'
      /usr/include/libindi/indipropertyview.h:315: Error: 'PropertyBasicBlob_at' is multiply defined in the generated target language module.
      /usr/include/libindi/indipropertybasic.h:114: Error: Previous declaration of 'PropertyBasicBlob_at'
      indiclientpython.i:71: Error: 'PropertyBasicBlob___getitem__' is multiply defined in the generated target language module.
      indiclientpython.i:109: Error: Previous declaration of 'PropertyBasicBlob___getitem__'
      indiclientpython.i:75: Error: 'PropertyBasicBlob___len__' is multiply defined in the generated target language module.
      indiclientpython.i:113: Error: Previous declaration of 'PropertyBasicBlob___len__'
      /usr/include/libindi/indiproperties.h:48: Warning 509: Overloaded method INDI::Properties::push_back(INDI::Property &&) effectively ignored,
      /usr/include/libindi/indiproperties.h:47: Warning 509: as it is shadowed by INDI::Properties::push_back(INDI::Property const &).
      /usr/include/libindi/indiproperties.h:74: Warning 512: Overloaded method INDI::Properties::begin() const ignored,
      /usr/include/libindi/indiproperties.h:71: Warning 512: using non-const method INDI::Properties::begin() instead.
      /usr/include/libindi/indiproperties.h:75: Warning 512: Overloaded method INDI::Properties::end() const ignored,
      /usr/include/libindi/indiproperties.h:72: Warning 512: using non-const method INDI::Properties::end() instead.
      /usr/include/libindi/indiproperties.h:89: Warning 512: Overloaded method INDI::Properties::operator *() const ignored,
      /usr/include/libindi/indiproperties.h:88: Warning 512: using non-const method INDI::Properties::operator *() instead.
      /usr/include/libindi/indiproperties.h:92: Warning 512: Overloaded method INDI::Properties::operator ->() const ignored,
      /usr/include/libindi/indiproperties.h:91: Warning 512: using non-const method INDI::Properties::operator ->() instead.
      /usr/include/libindi/indiproperties.h:94: Warning 503: Can't wrap 'operator std::vector<INDI::Property*>*' unless renamed to a valid identifier.
      /usr/include/libindi/indiproperties.h:95: Warning 503: Can't wrap 'operator const std::vector<INDI::Property*>*' unless renamed to a valid identifier.
      /usr/include/libindi/indiproperties.h:97: Warning 503: Can't wrap 'operator Properties*' unless renamed to a valid identifier.
      /usr/include/libindi/indiproperties.h:98: Warning 503: Can't wrap 'operator const Properties*' unless renamed to a valid identifier.
      Processing types...
      C++ analysis...
      Processing nested classes...
      Generating wrappers...
      error: command '/usr/bin/swig' failed with exit code 60
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyindi-client

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

The script exited abnormally, please try to run again...

**Comment by vastmeridian** [comment]
Hi

I'm getting the same error, Aaron.  I won't upload the logs as they are the same as above - unless there's something specific you'd like us to try?  This was a fresh build attempted today on a virtual machine running Ubuntu 20.04.5 LTS

**Comment by aaronwmorris** [comment]
There is definitely a problem with compiling pyindi-client right now.  I am investigating.

**Comment by vastmeridian** [comment]
> There is definitely a problem with compiling pyindi-client right now. I am investigating.
Let us know if there are any tests you need doing.

**Comment by aaronwmorris** [comment]
Merged #425 .  There are some upstream changes to pyindi-client that have not been added to an official release.  I updated the pip requirements files to pull from git instead.

**Comment by vastmeridian** [comment]
> Merged #425 . There are some upstream changes to pyindi-client that have not been added to an official release. I updated the pip requirements files to pull from git instead.

I'll do a git pull origin master and let you know.

**Comment by vastmeridian** [comment]
Thanks Aaron.  The ./setup.sh completes without error, now - but I forgot to go and get **indi_webcam_ccd**. Any chance you could include that in the list of drivers as it's needed for IP cameras?

**Comment by aaronwmorris** [comment]
It should automatically include any drivers found.  What did it list?

**Comment by vastmeridian** [comment]
indi-allsky lists every driver it finds, no problem.  I think it's when indiserver is installed, it doesn't pull down all the drivers.  I had to install indi_webcam separately and re-run setup.sh.

**Comment by aaronwmorris** [comment]
The compile of pyindi-client is working with 1.9.9, but it is still not working.  I will have to open an issue with the pyindi-client team.

**Comment by aaronwmorris** [comment]
Merged #426 so that the webcam driver is installed by default.

**Comment by vastmeridian** [comment]
I tried an install of #426 which went fine, but, even after a reboot, the build didn't read the config properly and tried to initialise /dev/video.  Here's an extract from the indi-allsky log:

`Nov 27 21:52:01 allskyvideo [INFO] MainProcess indi.serverConnected() #245: Server connected (localhost:7624)
Nov 27 21:52:01 allskyvideo [INFO] MainProcess indi.newDevice() #157: new device INDI Webcam
Nov 27 21:52:01 allskyvideo [INFO] MainProcess indi.newDevice() #157: new device Telescope Simulator
Nov 27 21:52:09 allskyvideo [INFO] MainProcess indi._findCcds() #430: Found device INDI Webcam
Nov 27 21:52:09 allskyvideo [INFO] MainProcess indi._findCcds() #435:  Detected ccd
Nov 27 21:52:09 allskyvideo [INFO] MainProcess indi._findCcds() #430: Found device Telescope Simulator
Nov 27 21:52:09 allskyvideo [INFO] MainProcess indi._findCcds() #435:  Detected telescope
Nov 27 21:52:09 allskyvideo [INFO] MainProcess indi._findCcds() #435:  Detected guider
Nov 27 21:52:09 allskyvideo [INFO] MainProcess indi.findCcd() #445: Found 1 CCDs
Nov 27 21:52:09 allskyvideo [WARNING] MainProcess allsky._initialize() #365: Connecting to device INDI Webcam
Nov 27 21:52:09 allskyvideo [INFO] MainProcess indi.newMessage() #242: new Message 2022-11-27T21:52:09: [INFO] Trying to connect to: /dev/video0, on device: video4linux2,v4l2 with 640x480 at 30 frames per second 
Nov 27 21:52:09 allskyvideo [INFO] MainProcess indi.newMessage() #242: new Message 2022-11-27T21:52:09: [INFO] Attempting to connect 
Nov 27 21:52:09 allskyvideo [INFO] MainProcess indi.newMessage() #242: new Message 2022-11-27T21:52:09: [INFO] Failed to open source. Check your settings: No such file or directory `

**Comment by aaronwmorris** [comment]
Merged #445 with the updated code to build the latest pyindi-client.  indi 1.9.9 is now officially released.

**Comment by aaronwmorris** [comment]
Closing this issue for now.
