### ISSUE TITLE
Additional fits header fields

### ISSUE THREAD

**Issue by sifank** [aaronwmorris/indi-allsky#429]
I added a section to your code to add a number of additional fields to the fits images (external temp/hum/dp, long/lat/time from a gps, etc).

That's not the way to do things (slaps my hand ...), as an upgrade will wipe that out.  So, could you add a 'hook' or some other mechanism to allow us to define other fields, plus their data?

**Comment by aaronwmorris** [comment]
I have some ideas on how to implement this.  Give me some time for this.

**Comment by sifank** [comment]
Thanks!


Sifan
Carpe Nocturnum ...

**Comment by sifank** [comment]
One idea ...  I could place the fields in a file, one line per field, formatted like "attribute, value"

**Comment by aaronwmorris** [comment]
I am going to close this in favor of #441
