### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by xrb12250** [aaronwmorris/indi-allsky#43]
Hi Aaron,

the setup script fails to successfully install indi-allsky:
**** Python virtualenv setup ****
mkdir: cannot create directory ‘/home/pi/indi-allsky/virtualenv’: Permission denied

Trying to use sudo or root fails because of your checking routine... 

Any ideas?

System is a pi 4 with a clean install raspbian light (buster)

**Comment by xrb12250** [comment]
Ok solved the problem with additional sudo's

`echo "**** Python virtualenv setup ****"
[[ ! -d "${ALLSKY_DIRECTORY}/virtualenv" ]] && sudo mkdir -m 755 "${ALLSKY_DIRECTORY}/virtualenv"
if [ ! -d "${ALLSKY_DIRECTORY}/virtualenv/indi-allsky" ]; then
    sudo virtualenv -p python3 ${ALLSKY_DIRECTORY}/virtualenv/indi-allsky
fi
`

**Comment by xrb12250** [comment]
> Ok solved the problem with additional sudo's
> 
> `echo "**** Python virtualenv setup ****" [[ ! -d "${ALLSKY_DIRECTORY}/virtualenv" ]] && sudo mkdir -m 755 "${ALLSKY_DIRECTORY}/virtualenv" if [ ! -d "${ALLSKY_DIRECTORY}/virtualenv/indi-allsky" ]; then sudo virtualenv -p python3 ${ALLSKY_DIRECTORY}/virtualenv/indi-allsky fi`

As expected, the whole installation is now somehow screwed up 😄 I'll give it another try

**Comment by aaronwmorris** [comment]
Did you perform the git checkout as root or something?  You probably just need to change the ownership of the git checkout.

`sudo chown -R pi /home/pi/indi-allsky`

**Comment by aaronwmorris** [comment]
I have updated the setup.sh script to fix the ownership of the git checkout if it is incorrect.

**Comment by xrb12250** [comment]
This works now, but there are some new problems now, I'll open a new issue.
