### ISSUE TITLE
request for rotating camera for 90 degree

### ISSUE THREAD

**Issue by pimmoon** [aaronwmorris/indi-allsky#431]
Hello,

I just would like to request, if possible, to be able to rotate the image for 90 degree (in addition to the existing vertical and horizontal flip).

If it is not too much trouble, it may be come in handy for some sites when you mistakenly install wrongly by 90 degree. It would be nice to fix it via the software.

Thank you so much for your consideration in advance.

**Comment by aaronwmorris** [comment]
Merged #432 to permit image rotation.

**Comment by pimmoon** [comment]
I verified this works! Thank you so much :)

**Comment by sifank** [comment]
Would this allow for arbitrary rotation?

**Comment by aaronwmorris** [comment]
This only allows for 90 degree offsets.

Arbitrary rotation is possible, I am not sure the outcome would be desirable.  With arbitrary rotation, you introduce areas with no data like this:

![](https://user-images.githubusercontent.com/17464290/180095177-803500ee-3266-430c-85cb-0c2247117f61.jpg)

**Comment by sifank** [comment]
Ah, thanks Aaron!

Sifan
Carpe Nocturnum ...

**Comment by aaronwmorris** [comment]
Closing this issue for now.  Let me know if there are any questions.
