### ISSUE TITLE
How to set the camera offset

### ISSUE THREAD

**Issue by sifank** [aaronwmorris/indi-allsky#459]
Is it possible to set the camera offset?  Is there an INDI Config that could do that?  Could you give me an example?

**Comment by aaronwmorris** [comment]
For ZWO cameras, you should be able to do the following.  I have read that the Pro cameras have a fixed offset, so I do not know if this will actually do anything if you are using the ASI294MC Pro

```
{
    "PROPERTIES" : {
        "CCD_CONTROLS" : {
            "Offset" : 10
        }
    },
    "SWITCHES" : {}
}

**Comment by sifank** [comment]
Thank you!

Sifan
Carpe Nocturnum ...
