### ISSUE TITLE
Enhancement:  have a log viewer page

### ISSUE THREAD

**Issue by sifank** [aaronwmorris/indi-allsky#482]
I can see where it would be handy to have a page that allows one to scroll back to, oh say, the last couple hundred lines of the log file, but normally would show the latest, ala 'tail -f' type of function.  This would help me support the people in the field, as they would not be connected to the internet and would be phoning in from the field.  They would be connecting with a tablet or phone to the allskysqm's hotspot (web) only.

**Comment by aaronwmorris** [comment]
Merged #486 with a log viewer

**Comment by dbainbridge** [comment]
The log viewer is nice!  Very convenient checking issues.

**Comment by aaronwmorris** [comment]
Fantastic!  I am glad it helps!

**Comment by sifank** [comment]
It's a great enhancement.  Thanks!!

Sifan Kahale
Carpe Nocturnum ...
