### ISSUE TITLE
Why separate "reload config" button?

### ISSUE THREAD

**Issue by dbainbridge** [aaronwmorris/indi-allsky#487]
If I am not mistaken when you update any configuration on the Config page you have to click the Save button at bottom of the Config page and then go to the System page, click on Services tab then click "Reload config" button.

Why doesn't the Reload config action automatically get triggered when you click the Save button on the Config page to begin with?  Or in other words why is applying a config change broken up into two separate steps?  This seems like it would be more straightforward and easier for people to understand if the config was reloaded whenever a user clicks Save on the config page.

**Comment by aaronwmorris** [comment]
Others have asked the same question.  I just do not like the idea of an implicit restart action.  Especially if you want to make changes to multiple settings and do not want to reload immediately.

While I would not call reloading "dangerous", if something is going to go wrong, this is the most likely time it will happen.

However, I have merged #488 which adds a config form element to enable reloading the service during a save.
