### ISSUE TITLE
Error notifications (especially out of disk space)

### ISSUE THREAD

**Issue by dbainbridge** [aaronwmorris/indi-allsky#499]
It would be helpful if there was some type of banner/notification on the web page when the system ran out of disk space.  Right now the live image says something about it being out of date.  You then need to check the System Info page to see that it ran out.  Along those lines a configurable low disk space warning on the web page would be helpful so you might be able to do something before it runs out of disk space.

**Comment by aaronwmorris** [comment]
Merged #503 with a new notification system that issues alerts for possible problems.

**Comment by aaronwmorris** [comment]
One of my cameras stopped taking images this morning and I got a notification when I logged in.  This seems to be working pretty well.

**Comment by vastmeridian** [comment]
Quick question, Aaron - does this notification pick up [ERROR] entries from the indi-allsky.log?

**Comment by aaronwmorris** [comment]
Not from the log, but the notification entries are added in some of the same places where the ERROR logs are generated.  I added notifications related to shutdown, disk usage, swap usage, file transfer, video failures, etc.  I am sure I will add more notifications that can be helpful.

**Comment by aaronwmorris** [comment]
Closing this issue for now.
