### ISSUE TITLE
Feature Request: Fetching sensor temp from imx477 from libcamera

### ISSUE THREAD

**Issue by Elliot-Ford** [aaronwmorris/indi-allsky#521]
The Pi-HQ camera's sensor has a built in temp sensor that can be fetched from the metadata output of libcamera (using the `--metadata` flag) when running image capture. Would be a nice addition as there's no good way to sample this sensor as the device is kept busy by the image generation.

**Comment by aaronwmorris** [comment]
I merged your change and updated the code #533 to just parse the JSON directly instead of parsing the data via grep.

**Comment by Elliot-Ford** [comment]
Cool, thanks for taking a look at this. I like the switch to the json, lot cleaner than the grep approach. Closing.
