### ISSUE TITLE
Focus Mode enhancement request: Graph the focus 'score' 

### ISSUE THREAD

**Issue by vastmeridian** [aaronwmorris/indi-allsky#524]
Just a suggestion: Since we are trying to 'peak' the focus to get the sharpest image, is it possible (or, indeed, worth it) to graph the focus score alongside the focus mode image so that we can see when we've 'reached our peak'?

**Comment by aaronwmorris** [comment]
Merged #547 .  It is not as pretty as I wanted as I could not get the chart canvas element to size correctly.... but it works.

**Comment by aaronwmorris** [comment]
Closing this issue for now.
