### ISSUE TITLE
Switch off logon at web interface?

### ISSUE THREAD

**Issue by jkoenig72** [aaronwmorris/indi-allsky#530]
Hi Aaron,

just asking - is there a way to disable logon completly?

Thanks!

**Comment by aaronwmorris** [comment]
You should be able to add the following to /etc/indi-allsky/flask.json.  I have not tested this, so let me know.

```
"LOGIN_DISABLED" : true
```
Note:  may require a trailing comma depending on where you add it.

**Comment by aaronwmorris** [comment]
I have added the `LOGIN_DISABLED` option (default false) in the repo for reference.

In merge #532 I also updated the processing of the flask.json config file.  Previously, the setup.sh script would overwrite the flask.json, losing any customizations.  In this change, the setup.sh script now attempts to merge the changes so hopefully, any customizations you make will be maintained.

**Comment by jkoenig72** [comment]
Awesome, thanks!

**Comment by aaronwmorris** [comment]
Closing this for now.
