### ISSUE TITLE
possible information/security issue: 15 year old python bug found that is causing concern

### ISSUE THREAD

**Issue by vastmeridian** [aaronwmorris/indi-allsky#531]
This may not apply to you, Aaron, but I found this in my feed today:

https://www.itpro.co.uk/development/open-source/369920/350000-open-source-projects-vulnerable-15-year-old-python-bug

**Comment by aaronwmorris** [comment]
Thank you for submitting this.  I do not think indi-allsky is vulnerable as there is no code for handling tar files.

**Comment by vastmeridian** [comment]
No problem, Aaron.  I'll close as resolved.

**Comment by vastmeridian** [comment]
No problem, Aaron.  I'll close as resolved.
