### ISSUE TITLE
fix: writing config file to temp file

### ISSUE THREAD

**Issue by Elliot-Ford** [aaronwmorris/indi-allsky#537]
## Issue
When the camera's disk is full the saving of the config file ends up zeroing the config file on disk.

## Proposed fix
Instead of immediately overwriting the config to disk if we write it to a temporary file and then on success move it over the config file it would ensure that there is enough space on disk and wouldn't wipe the existing config

**Comment by aaronwmorris** [comment]
Ouch

**Comment by aaronwmorris** [comment]
Merged #539 to address this issue.

Configs are now written to a temp file within the config folder to ensure there is enough space.  The existing config is also copied to a (single) backup file for safety.

**Comment by Elliot-Ford** [comment]
Thanks for the quick fix! Closing.
