### ISSUE TITLE
Password and login

### ISSUE THREAD

**Issue by Frankastro85** [aaronwmorris/indi-allsky#55]
Hello,
My installation is successful (I think) but I can't access to the web page https://raspberrypi/indi-allsky/.
I don't know the login and pwd. Is-it the same of the Pi ?
Thank you

**Comment by Frankastro85** [comment]
Hmmm, ok, I found it on the site of Thomas Jacquin :-)

**Comment by aaronwmorris** [comment]
Excellent.  I used the same authentication credentials.

It is documented in the github readme:  https://github.com/aaronwmorris/indi-allsky#web-interface

**Comment by Frankastro85** [comment]
Yes, perfect.
So now, on my Raspberry (new card), I've installed both Allsky -> Thomas Jacquin and You.
The Allsky run perfectly but I can't run your version.
How can I test your Indi-Allsky ?
Thank you.

**Comment by aaronwmorris** [comment]
Both software will not run simultaneously.  I believe Thomas Jacquin's Allsky uses lighttpd web server where mine installs Apache.  If you re-run my setup.sh script, it should disable (not uninstall) Thomas Jacquin's Allsky components and services.

**Comment by Frankastro85** [comment]
Ok, I'll try that.
Thank you.

**Comment by ruirigel** [comment]
I've been looking for where to change the password but can't find it. Any suggestions?

**Comment by aaronwmorris** [comment]
You can change the password using the following command:

`htpasswd /etc/indi-allsky/apache.passwd admin`
