### ISSUE TITLE
flask command not found

### ISSUE THREAD

**Issue by Trigger-broom-289** [aaronwmorris/indi-allsky#558]
On Ubuntu 22.04 I get the following but can't figure out how to resolve it

Synchronizing state of apache2.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable apache2
**** Setup HTDOCS folder ****
**** Setup image folder ****
**** Setup DB ****
./setup.sh: line 1848: flask: command not found

The script exited abnormally, please try to run again...

------
~/GitHubstuff/indi-allsky$ pip3 list | grep -i flask
Flask                  2.2.2
Flask-Login            0.6.2
Flask-Migrate          4.0.4
Flask-SQLAlchemy       3.0.3
Flask-WTF              1.1.1

**Comment by aaronwmorris** [comment]
Is this just a regular x86_64 system?
