### ISSUE TITLE
Can't Delete Images

### ISSUE THREAD

**Issue by Jquitadamo** [aaronwmorris/indi-allsky#567]
Everytime I try and delete all images/timelapses (to start fresh) they all just show back up after a reboot. I cant figure out what's going on for the life of me...

**Comment by aaronwmorris** [comment]
I think your sdcard has failed.  I have had this happen to me before.  The system will boot and work, you can delete files and change files, but if you reboot, everything is reset back to the original state.

**Comment by aaronwmorris** [comment]
Closing this issue for now.  Let me know if there is anything else I can do for you.
