### ISSUE TITLE
Clarify ADU Region of Interest array

### ISSUE THREAD

**Issue by gilesco** [aaronwmorris/indi-allsky#57]
What are x1, y1, x2, y2

For instance in image of 1280 x 960

Would values of 200,200,1180,860 crop 200 pixels on the top and left and crop 100 pixels around the border on the bottom and right?

**Comment by aaronwmorris** [comment]
You got it!  (x1, y1) are the top left coordinates and (x2, y2) are the bottom right.

Just an FYI, the defaults do not use the whole image for the ADU calculation, it uses about 70% of the central region to exclude the edges.

https://github.com/aaronwmorris/indi-allsky/blob/master/indi_allsky/image.py#L853
