### ISSUE TITLE
Feature Request: INDI GPS USB and NTP Server

### ISSUE THREAD

**Issue by HxPI** [aaronwmorris/indi-allsky#600]
Is it possible to connect a USB GPS dongle, like the u-Blox7 USB GPS variants, and allow INDI to connect to it for location and time information? Would it also be possible to setup an internal NTP server to use this time information or can INDI provide the time information to indi-allsky? There are devices like the LeoNTP that will provide a portable NTP service but was wondering if this can be done with the RPi using a simple GPS USB dongle.

**Comment by HxPI** [comment]
Never mind. I see there is a GPS time sync option in configuration webpage. Not sure about the GPSd install requirement. Is that something I have to do manually or does it happen automatically when this feature is enabled and/or a GPS device is detected?

**Comment by aaronwmorris** [comment]
The script `./misc/setup_gpsd.sh` that should do most of the gpsd install and setup for you.

**Comment by HxPI** [comment]
I’ll try that. Thanks.

**Comment by aaronwmorris** [comment]
Yes, it will disable the normal systemd timesyncd.

**Comment by HxPI** [comment]
So there’s no way to restore the normal systems timesyncd after enabling GPSd? I’d rather leave the system the way it is than permanently change it.

**Comment by aaronwmorris** [comment]
It is better to just sync time using ntp and gpsd directly than let indi-allsky do it.

https://github.com/aaronwmorris/indi-allsky/wiki/GPSd-NTP-Time-Sync

**Comment by HxPI** [comment]
OK thanks. I’ll close this.
