### ISSUE TITLE
Recent update: INDI-allsky confusion over image location / camera name

### ISSUE THREAD

**Issue by StarGeezerPhil** [aaronwmorris/indi-allsky#656]
After a recent update images started to get stored in a new location (/images/ccd_49e24657-c476-4488-85ff-91bed9eae2e2) rather than just /images.

This hasn't seemed to be a problem until today when the timelapse generation script seems to be getting confused:

Yesterday's timelapse generated fine, but the night timelapse (etc.) failed due to the image folder:
![image](https://user-images.githubusercontent.com/94135145/226568059-a9c38882-e7ae-4e2d-ab2f-c81f2412087d.png)

**Comment by aaronwmorris** [comment]
I noticed that too.  Let me know what happens tonight.  My cameras had a similar issue when I upgraded the code, but it was only the one time.

**Comment by StarGeezerPhil** [comment]
Did yours revert back to saving into /images or has yours continued within the subfolder?

All images since I updated on 10 March have been within the /ccd_(guid)/ subfolder.

I'll let you know what happens with the timelapse for today/tonight 👍

**Comment by aaronwmorris** [comment]
The GUID name is the new standard.

The tasks in the screenshot, did you initiate those manually or were those automatic tasks?

**Comment by StarGeezerPhil** [comment]
I *think* they were initialized automatically. All the manual tasks I tried after failed.

Today's daytime timelapse has generated - but only the first few hours (been running ok all day).

**Comment by StarGeezerPhil** [comment]
Update @aaronwmorris: manually re-generating yesterday's daytime timelapse worked, and the night time one worked automatically this morning.

Seems hit and miss - I'll let you know this evening.

**Comment by aaronwmorris** [comment]
After re-reading the screenshot above, I think I understand the error.  For some reason a task to create the night timelapse for 3/21, but it was 8:23am.  Night had not started, therefore the destination folder did not yet exist.

**Comment by StarGeezerPhil** [comment]
Ah - sorry yes, that must have been a manual one (and I must have selected the wrong date), but the issue does stay the same.

A subsequent one for the same period:
![image](https://user-images.githubusercontent.com/94135145/226985772-9e4a6c6d-eaf1-4b4e-bc9a-f9f9369230a2.png)

Hopefully it's just a one-off - I still can't get 20 March to generate, but they have done since.

**Comment by aaronwmorris** [comment]
It could be a corrupted image file.  You would have to find the exception.

**Comment by aaronwmorris** [comment]
Closing this issue for now.  Reopen if there are any other issues.
