### ISSUE TITLE
Suggestion: Watchdog integration/instructions

### ISSUE THREAD

**Issue by WarrenSchultz** [aaronwmorris/indi-allsky#677]
I've got my setup running inside to test for stability long-term before deploying it somewhere inconvenient to reach later :)

Last night I had a hard lock on the system, and it was unreachable, except for ping.

I went ahead and enabled this, and we'll see if I have any further issues, but thought it might be useful to either integrate it into the install process, or at least document it here to match the config for future users.

https://medium.com/@arslion/enabling-watchdog-on-raspberry-pi-b7e574dcba6b

**Comment by WarrenSchultz** [comment]
I'd looked but not seen it somehow. My mistake! :)

**Comment by aaronwmorris** [comment]
No problem.  The instructions are not invalid.  Some people might not like using systemd, but it is super easy to use and I can confirm it has worked well for me.
