### ISSUE TITLE
Instalar em um Computador usando ASI120mc

### ISSUE THREAD

**Issue by lumdiniz** [aaronwmorris/indi-allsky#679]
Olá... tenho um computador com armbian e uma asi120mc. eu consigo rodar esse programa com esse conjunto?
nao estou conseguindo instalar.
Grato
Luciano
Brazil

**Comment by aaronwmorris** [comment]
Yes, you can use Armbian with the ASI120 camera.  You will have to manually compile INDI, but I have a script that automatically does that for you.  `./misc/build_indi.sh`

**Comment by lumdiniz** [comment]
> Sim, você pode usar Armbian com a câmera ASI120. Você terá que compilar o INDI manualmente, mas tenho um script que faz isso automaticamente para você. `./misc/build_indi.sh`

ok... eu nao entendo muito de linux como faz o campular do INDI.... essa linha ./misc/build_indi.sh eu digito onde? fala que é invalido

Grato

**Comment by aaronwmorris** [comment]
The script will be in the indi-allsky repo once you perform a `git clone`

**Comment by lumdiniz** [comment]
> O script estará no repositório indi-allsky assim que você executar um`git clone`

obrigado... eu troquei para o ubuntu versao 20 ... instalou tudo automatico nao tive problemas..... esta funcionando agora... gostei muito das funcoes que tem..... existe um manual resumido de como configurar para meteoros mascaras e outros?

**Comment by aaronwmorris** [comment]
Look through the wiki pages.  I have some functions documented, but I still have some work to do for documentation:

https://github.com/aaronwmorris/indi-allsky/wiki

https://github.com/aaronwmorris/indi-allsky/wiki/Detection-Masks
