### ISSUE TITLE
Stacking info on image not correct

### ISSUE THREAD

**Issue by RoySalisbury** [aaronwmorris/indi-allsky#686]
The label template has the "Stacking {stack_method:s}" but even when stacking is enabled, this always says "off"

I have included screen shots to show the configuration and result.

![Screenshot 2023-04-08 at 9 05 51 PM](https://user-images.githubusercontent.com/12501943/230753834-dd46671c-1d66-4b7a-b243-cb7c8f90d8cd.png)
![Screenshot 2023-04-08 at 9 06 29 PM](https://user-images.githubusercontent.com/12501943/230753843-81ae1484-8c6e-4626-a289-8e7fa596e451.png)
![Screenshot 2023-04-08 at 9 08 42 PM](https://user-images.githubusercontent.com/12501943/230753868-9c92f535-f3fc-48e3-a189-6245fabe079c.png)

**Comment by aaronwmorris** [comment]
Merged #687.  This one was tough to spot.

**Comment by aaronwmorris** [comment]
Closing this for now.  Let me know if it does not work for you.
