### ISSUE TITLE
Service keeps crashing

### ISSUE THREAD

**Issue by phatwila** [aaronwmorris/indi-allsky#690]
Hello,
I started getting this in the log, and the indi-allsky crashes. Let me know if you need more information.

[indi-sky-log.txt](https://github.com/aaronwmorris/indi-allsky/files/11201934/indi-sky-log.txt)

**Comment by aaronwmorris** [comment]
If you do not have a GPS module, re-run the setup.sh and select `None` for the GPS server.

**Comment by aaronwmorris** [comment]
And restart the `indiserver` service (or reboot)

```
systemctl --user restart indiserver
```

**Comment by aaronwmorris** [comment]
I was able to replicate this error by building the wrong version of the pyindi-client module.  Run `./misc/rebuild_pyindi-client.sh` and ensure 1.9.7 is selected.

For the GPS module, make sure GPSd is installed and running.  There is a script for setting that up at `./misc/setup_gpsd.sh`
