### ISSUE TITLE
No Image display in clean install

### ISSUE THREAD

**Issue by ispybadguys** [aaronwmorris/indi-allsky#711]
I rebuilt Indi-allsky from a clean copy of Astroberry to solve an issue with MQTT and I don't get any images. When I ran it it get no images displayed or charts. It reinstalled it again and the same happens. The log shows the camera is working but there is an error:

Image worker exception: AttributeError: 'Fraction' object has no attribute 'as_integer_ratio'

Here is part of the log:

Apr 25 07:36:06 astroberry [INFO] MainProcess allsky._queueManualTasks() #2426: Checking for manually submitted tasks
Apr 25 07:36:06 astroberry [INFO] MainProcess indi.getTelescopeRaDec() #833: Telescope Coord: RA 20.72, Dec 35.15
Apr 25 07:36:06 astroberry [INFO] MainProcess indi.getCcdTemperature() #848: Sensor temperature: 14.5
Apr 25 07:36:06 astroberry [INFO] MainProcess allsky.detectMoonMode() #1608: Moon altitude: -21:41:23.6, phase 28.7%
Apr 25 07:36:06 astroberry [INFO] MainProcess allsky.detectNight() #1591: Sun altitude: 14:06:46.5
Apr 25 07:36:06 astroberry [WARNING] MainProcess image._load_detection_mask() #1482: No detection mask defined
Apr 25 07:36:06 astroberry [INFO] MainProcess allsky._startImageWorker() #775: Starting ImageWorker process 4
Apr 25 07:36:06 astroberry [ERROR] MainProcess allsky._startImageWorker() #768: Image worker exception: 
Apr 25 07:36:06 astroberry [ERROR] MainProcess allsky._startImageWorker() #768: Image worker exception: AttributeError: 'Fraction' object has no attribute 'as_integer_ratio'
Apr 25 07:36:06 astroberry [ERROR] MainProcess allsky._startImageWorker() #768: Image worker exception:     focal_length = Fraction(camera.lensFocalLength).limit_denominator().as_integer_ratio()
Apr 25 07:36:06 astroberry [ERROR] MainProcess allsky._startImageWorker() #768: Image worker exception:   File "/home/astroberry/indi-allsky/indi_allsky/image.py", line 361, in processImage
Apr 25 07:36:06 astroberry [ERROR] MainProcess allsky._startImageWorker() #768: Image worker exception:     self.processImage(i_dict)
Apr 25 07:36:06 astroberry [ERROR] MainProcess allsky._startImageWorker() #768: Image worker exception:   File "/home/astroberry/indi-allsky/indi_allsky/image.py", line 257, in saferun
Apr 25 07:36:06 astroberry [ERROR] MainProcess allsky._startImageWorker() #768: Image worker exception:     self.saferun()
Apr 25 07:36:06 astroberry [ERROR] MainProcess allsky._startImageWorker() #768: Image worker exception:   File "/home/astroberry/indi-allsky/indi_allsky/image.py", line 228, in run
Apr 25 07:36:06 astroberry [ERROR] MainProcess allsky._startImageWorker() #768: Image worker exception: Traceback (most recent call last):
Apr 25 07:36:06 astroberry [INFO] MainProcess allsky.run() #1043: Exposure state: OK
Apr 25 07:36:06 astroberry [INFO] MainProcess allsky.run() #1042: Camera last ready: 2.7s
Apr 25 07:36:04 astroberry [INFO] ImageWorker003 image.processImage() #351: Image: 1304 x 976
Apr 25 07:36:03 astroberry [INFO] ImageWorker003 sqm.calculate() #42: Weighted SQM average: 101301.03
Apr 25 07:36:03 astroberry [INFO] ImageWorker003 sqm.calculate() #37: Raw SQM average: 3683.68

**Comment by aaronwmorris** [comment]
Sorry about that, apparently python 3.6 does not support as_integer_ratio() for fractions.

Merged #712 to fix.
