### ISSUE TITLE
Problems running usertools.py

### ISSUE THREAD

**Issue by vastmeridian** [aaronwmorris/indi-allsky#726]
Running usertools.py from the command line gives me the following error:

```
user@allsky:~/indi-allsky/misc$ ./usertool.py deleteuser -u viewer
Traceback (most recent call last):
  File "./usertool.py", line 8, in <module>
    from passlib.hash import argon2
ModuleNotFoundError: No module named 'passlib'
user@allsky:~/indi-allsky/misc$
```
I'd had the same problem running the command as per the wiki.

Looks like I'm going to have to start from scratch.

**Comment by aaronwmorris** [comment]
You just need to first activate the virtualenv...

```
source virtualenv/indi-allsky/bin/activate

./usertool.py deleteuser -u viewer
```

**Comment by vastmeridian** [comment]
Thank you.  Issue closed.
(Maybe a mention on the wiki - or did I miss it?)

**Comment by vastmeridian** [comment]
Thank you.  Issue closed.
(Maybe a mention on the wiki - or did I miss it?)
