### ISSUE TITLE
libcamera extra options being ignored

### ISSUE THREAD

**Issue by uotw** [aaronwmorris/indi-allsky#744]
Hi, trying to get the most lean config possible since I'm running RPi 3B+ and HQ Camera, so I added this option to the _libcamera extra options_ field `--mode 1014:760`. I am using the libcamera IMX477 driver with DNG capture, so this should get appended to the `libcamera-still...`capture command. Here's what I'm seeing in the log:

> May  8 09:50:21 raspberrypi [INFO] MainProcess libcamera.setCcdExposure() #183: image command: libcamera-still --immediate --nopreview --encoding jpg --quality 95 --gain 16 --shutter 3669 --metadata /tmp/tmplvy7bqnv.json --metadata-format json --mode 1014:760 --output /tmp/tmp0ohzizp7.jpg

**Comment by aaronwmorris** [comment]
The option is there, it is appended right before the last option which is always --output
