### ISSUE TITLE
SQM_ROI or ADU_ROI

### ISSUE THREAD

**Issue by gilesco** [aaronwmorris/indi-allsky#75]
sqm.py tries to fetch SQM_ROI from config.json

However, config.json only has ADU_ROI and does not define SQM_ROI

I tried changing ADU_ROI to SQM_ROI in config.json, but that causes an error elsewhere.

For time being have added both ADU_ROI & SQM_ROI to config.json, appears to work.

Don't know if we need two different settings for this, or whether we can just change SQM_ROI in sqm.py to ADU_ROI.

**Comment by gilesco** [comment]
SQM_ROI also present in stars.py

**Comment by aaronwmorris** [comment]
This is my fault.  This was an optional and undocumented config option that I completely missed in the config form.

Merged #77 with the updated config file and form options.

**Comment by aaronwmorris** [comment]
The more I think about it... I think your code change might have been the correct action instead of me adding the new options.
