### ISSUE TITLE
SSH access

### ISSUE THREAD

**Issue by evripidis** [aaronwmorris/indi-allsky#765]
Hello!

I’m quite sure that I haven’t made any changes on the credentials or usernames etc.

I am trying to access my RPI from a remote location via SSH (SSH is opt-in). 

What are my unit's credentials? Should be for example the RPI’s defaults? I can’t recall if the setup changed the username or password. :-(

**Comment by aaronwmorris** [comment]
indi-allsky does not touch the user credentials.  If you have not changed them, the password would be the defaults `pi` and `raspberry`.

Note:  On the latest version of Raspbian, it forces you to create a separate user and password.

**Comment by evripidis** [comment]
Thank you for clarifying that !
