### ISSUE TITLE
Forgot the PSW Web User

### ISSUE THREAD

**Issue by Aldopm99** [aaronwmorris/indi-allsky#766]
I changed but forgot the PSW of the Web User Interface. has howtorecover or will Ihave toreinstall SW ?

**Comment by aaronwmorris** [comment]
You can change the password from the CLI.

https://github.com/aaronwmorris/indi-allsky/wiki/Web-Interface-Password

**Comment by aaronwmorris** [comment]
Closing this for now.  Let me know if this did not work.
