### ISSUE TITLE
Image Stretch and Text Overlay

### ISSUE THREAD

**Issue by HxPI** [aaronwmorris/indi-allsky#777]
It appears the text overlay is affected by the new stretch image function. When stretch is enabled in night mode, the text is washed out and unreadable. When disabled, the text is clear and legible. Please verify whether the stretch is affecting the text overlay. I would assume the text overlay would take place after the image stretch. Also, it appears stretch does not affect the raw image output, i.e. tiff or fits; is this correct? Thank you.

**Comment by aaronwmorris** [comment]
That is odd.  The text label is applied well after the stretch.  Can you post some screenshots?

**Comment by HxPI** [comment]
Nevermind. I opened the images directly from storage and the text overlay is fine. The text overlay on the web interface become readable from time to time. Must be the way the webpage is displaying them.
