### ISSUE TITLE
Sony Camera

### ISSUE THREAD

**Issue by Marmi86** [aaronwmorris/indi-allsky#79]
Hello,
I am getting a Sony RX 100 M1 next week which I would like to use for the indi-allsky system, should I send you the data via indi_getprop?

**Comment by aaronwmorris** [comment]
Please do.  If it is supported by indi and libgphoto2 (with the right features) we should be able to make it work.

**Comment by aaronwmorris** [comment]
Closing this issue for now.  Let me know if you need help with the camera.
