### ISSUE TITLE
Smoke Rating Label Issue

### ISSUE THREAD

**Issue by Jquitadamo** [aaronwmorris/indi-allsky#873]
Error when adding {smoke_rating:s} to image label

![Screenshot_20230809_174833_Chrome.jpg](https://github.com/aaronwmorris/indi-allsky/assets/114357349/4733992b-0371-4f1b-9189-8822484d0e12)

**Comment by aaronwmorris** [comment]
You probably just need to update to the latest code and restart.

**Comment by Jquitadamo** [comment]
Sorry, I should have mentioned, I'm currently on v7.2

**Comment by aaronwmorris** [comment]
The smoke rating was a very recent update, so the latest code will be necessary.

**Comment by Jquitadamo** [comment]
Pulled down the latest and this is working now. Thanks!

Jason
