### ISSUE TITLE
Exposure period values don't make sense

### ISSUE THREAD

**Issue by milesnz** [aaronwmorris/indi-allsky#877]
Hi Aaron,
When using the following settings I get the error as shown in the screenshot which don't make sense to me.
If this is not a bug would you mind explaining the logic to me please.
I was expecting to be able to set my day period different to the night period, and also to be able to make them less than the maximum exposure?

regards
Miles

Max Exposure = 60
        error "Exposure period cannot be greater than the night period"
Exposure period night = 30
        error "Period is less than maximum exposure"
Exposure period day = 30

 
![Capture](https://github.com/aaronwmorris/indi-allsky/assets/30332971/07c6b740-b248-4c64-be35-c15d24b24c26)

**Comment by aaronwmorris** [comment]
Update to the latest code and those checks are no longer in place.

jkoenig72 convinced me to remove those in https://github.com/aaronwmorris/indi-allsky/issues/795

**Comment by milesnz** [comment]
awesome, thank you
