### ISSUE TITLE
Stacking "disabled" during daytime

### ISSUE THREAD

**Issue by evripidis** [aaronwmorris/indi-allsky#890]
Hello!

Why is stacking not disabled during the daytime? Am I missing any extra setting?

![Screenshot 2023-08-15 at 09 56 00](https://github.com/aaronwmorris/indi-allsky/assets/216827/6f5c8ea0-34ce-4ff1-894b-9a38079c1760)

EDIT:

Okk....That's weird.. I've just noticed that the system is switched on to Night Mode. But why?
![Screenshot 2023-08-15 at 10 00 04](https://github.com/aaronwmorris/indi-allsky/assets/216827/c6c5d1fb-55fa-4442-8f14-c2debccb8892)

**Comment by evripidis** [comment]
For a strange reason, Lat /Long had changed. False alarm.

**Comment by aaronwmorris** [comment]
That is strange.  Let me know if it happen again.
