### ISSUE TITLE
Have image processing algiorithms changed recently?

### ISSUE THREAD

**Issue by vastmeridian** [aaronwmorris/indi-allsky#950]
In updating to #937 I have noticed that the images seem to be more 'processed' as the two shots below indicate.  Maybe I missed an announcement.

This image was typical of the pre #937 build
![Pre-937](https://github.com/aaronwmorris/indi-allsky/assets/15128874/7506f87a-89d4-42c8-bf31-4f3ab739268a)

Whereas this image has become more prominent since upgrading to #937.
![Post-937](https://github.com/aaronwmorris/indi-allsky/assets/15128874/4b62bedc-5fde-4473-b3ca-360f34ce1f13)

Have the image processing algorithms changed recently?  It looks like I will need to re-think my settings.

**Comment by aaronwmorris** [comment]
I did change the default Field of View used for the SQM calculations and processing.  I changed the default to the central 50% of the image where it used to be 66%.  If you change the SQM FoV to 66% on the Processing Tab, it should function like it used to for you.

Another workaround is creating a detection mask, which will use the mask for the borders of the calculations.

This most heavily affects the stretching algorithm.

**Comment by vastmeridian** [comment]
Following on from this and my post on the AllSky group on Facebook, I'll  try the new release and report my findings here.  The 'false colouring' does seem related to SCNR as disabling this does stop the colouring.  I will also try setting the colour saturation setting back to 1.0, as 1.5 does seem to over-colour my stars.

![image](https://github.com/aaronwmorris/indi-allsky/assets/15128874/ba062da2-8541-4900-af10-6a55796788ef)

**Comment by aaronwmorris** [comment]
Those colors actually look very good.

I have learned quite a bit more about numpy since originally implementing the SCNR.  I now know how to deal with the integer overflows.

**Comment by vastmeridian** [comment]
I've updated the software following your note and I'll see how things go, so thank you as always for the quick response.

To me the colours look too magenta, if you follow.  I almost want to rebalance the colours.  Maybe I will do that once things have settled down with the processing.

**Comment by vastmeridian** [comment]
Well, I'm still getting very odd colours...

I've lowered the gains in case I'm getting a lot of large-value pixels and I've got CLAHE and SCNR disabled; stretching on, but not excessively.  My settings are:

Night Gain | 1800
Moon Mode Gain | 1400
CLAHE Clip Limit | off
CLAHE Grid Size | off
16-bit Contrast   Enhance | off
Enable Stretching | on
Stretching Gamma | 1.5
Stretching Std   Deviations | 1.0
Moon Mode   Stretching | on
Daytime Stretching | off
Stretching split   screen | Off
Bayer Pattern | RGGB
SCNR (green   reduction) |  
Red Balance Factor | 0.6
Green Balance   Factor | 0.8
Blue Balance   Factor | 1.0
Auto White Balance | on
Saturation Factor | 1.5

![ccd1_20230926_213255](https://github.com/aaronwmorris/indi-allsky/assets/15128874/e3b11446-0a09-4516-8873-474d2640e3bc)

The histogram is
![Untitled](https://github.com/aaronwmorris/indi-allsky/assets/15128874/65c2ae90-6d69-4a2f-b28d-6dfa87986989)

Is there a setting I can use to get the raw out-of-camera FITS file so that I can see what the pixels are before processing?

**Comment by aaronwmorris** [comment]
The histogram may be a bit deceiving, too.  I just remembered that the histogram is generated from a crop of the center of the image (trying to exclude things like trees on the edges).

**Comment by vastmeridian** [comment]
I'm still bemused by the incredibly strong colouring I am getting.  I've reduced the gain of the camera; turned off CLAHE and have no colour saturation enabled - and I am still getting very strong colours in my images which are not present in the FITS versions of the images.

Is there a way of setting all processing settings to their defaults in case I've missed a setting?  I can then start my processing set up from scratch again.

**Comment by aaronwmorris** [comment]
There is a new feature in the latest release where you can test processing settings.  If you have a FITS version saved of an image (in the database), you can select `FITS Processing` in the image viewer (at the bottom) to bring up a page where you can test different processing settings.  That might help you track it down.

**Comment by vastmeridian** [comment]
I think this can be shut down as an issue now.

Thanks for your help
